// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miles",acronym:"mi"},kilometers:{displayText:"Kilometer",acronym:"km"},feet:{displayText:"Fot",acronym:"ft"},meters:{displayText:"Meter",acronym:"m"}},searchSetting:{searchSettingTabTitle:"S\u00f8keinnstillinger",defaultBufferDistanceLabel:"Angi standard bufferavstand",maxBufferDistanceLabel:"Angi maksimal bufferavstand",bufferDistanceUnitLabel:"Enheter for bufferavstand",defaultBufferHintLabel:"Hint: Angi standardverdi for bufferglidebryteren",
maxBufferHintLabel:"Hint: Angi maksimumsverdi for bufferglidebryteren",bufferUnitLabel:"Hint: Angi enhet for oppretting av buffer",selectGraphicLocationSymbol:"Adresse- eller lokasjonssymbol",graphicLocationSymbolHintText:"Hint: Symbol for adresse det er s\u00f8kt etter, eller lokasjon det er klikket p\u00e5.",fontColorLabel:"Velg skriftfarge for s\u00f8keresultater",fontColorHintText:"Hint: Skriftfarge for s\u00f8keresultater",zoomToSelectedFeature:"Zoom til det valgte geoobjektet",zoomToSelectedFeatureHintText:"Hint: Zoom til det valgte geoobjektet i stedet for bufferen",
intersectSearchLocation:"Returner kryssende polygon(er)",intersectSearchLocationHintText:"Hint: Returner  polygon(er) som inneholder lokasjonen det er s\u00f8kt etter, i stedet for polygoner i bufferen",bufferVisibilityLabel:"Angi buffersynlighet",bufferVisibilityHintText:"Hint: Bufferen vises i kartet",bufferColorLabel:"Angi buffersymbol",bufferColorHintText:"Hint: Velg farge og gjennomsiktighet for buffer",searchLayerResultLabel:"Tegn kun resultater for valgt lag",searchLayerResultHint:"Hint: Kun laget som er valgt i s\u00f8keresultatene tegnes p\u00e5 kartet"},
layerSelector:{selectLayerLabel:"Velg et eller flere s\u00f8kelag",layerSelectionHint:"Hint: Bruk Angi-knappen til \u00e5 velge et eller flere lag",addLayerButton:"Angi"},routeSetting:{routeSettingTabTitle:"Innstillinger for veibeskrivelser",routeServiceUrl:"Rutetjeneste",buttonSet:"Angi",routeServiceUrlHintText:"Hint: Klikk p\u00e5 Angi for \u00e5 bla gjennom og velge en rutetjeneste",directionLengthUnit:"Lengdeenheter for rutebeskrivelse",unitsForRouteHintText:"Hint: Brukes til \u00e5 vise enheter for rute",
selectRouteSymbol:"Velg symbol for rutevisning",routeSymbolHintText:"Hint: Brukes til \u00e5 vise linjesymbol for ruten",routingDisabledMsg:"Kontroller at ruteberegning er aktivert i ArcGIS Online-elementet hvis du vil aktivere rutebeskrivelser."},networkServiceChooser:{arcgislabel:"Legg til fra ArcGIS Online",serviceURLabel:"Legg til tjeneste-URL",routeURL:"Rute-URL",validateRouteURL:"Valider",exampleText:"Eksempel",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",
hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Angi en gyldig rutetjeneste",rateLimitExceeded:"Hastighetsbegrensningen er overskredet. Pr\u00f8v p\u00e5 nytt senere.",errorInvokingService:"Brukernavnet eller passordet er feil."},errorStrings:{bufferErrorString:"Angi en gyldig numerisk verdi.",selectLayerErrorString:"Velg laget eller lagene det skal s\u00f8kes i.",invalidDefaultValue:"Standard bufferavstand kan ikke v\u00e6re tom. Angi bufferavstanden.",
invalidMaximumValue:"Maksimum bufferavstand kan ikke v\u00e6re tom. Angi bufferavstanden.",defaultValueLessThanMax:"Angi standard bufferavstand med maksimumsgrensen",defaultBufferValueGreaterThanZero:"Du m\u00e5 angi en standard bufferavstand som er h\u00f8yere enn 0",maximumBufferValueGreaterThanZero:"Du m\u00e5 angi en maksimum bufferavstand som er h\u00f8yere enn 0"},symbolPickerPreviewText:"Forh\u00e5ndsvisning:",_localized:{}}});