// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Mile",acronym:"mi"},kilometers:{displayText:"Kilometer",acronym:"km"},feet:{displayText:"Fot",acronym:"fot"},meters:{displayText:"Meter",acronym:"m"}},searchSetting:{searchSettingTabTitle:"S\u00f6kinst\u00e4llningar",defaultBufferDistanceLabel:"Ange ett standardv\u00e4rde f\u00f6r buffertavst\u00e5nd",maxBufferDistanceLabel:"Ange maximalt buffertavst\u00e5nd",bufferDistanceUnitLabel:"Enheter f\u00f6r buffertavst\u00e5nd",defaultBufferHintLabel:"Tips: Ange standardv\u00e4rde f\u00f6r buffertreglaget",
maxBufferHintLabel:"Tips: Ange maxv\u00e4rde f\u00f6r buffertreglaget",bufferUnitLabel:"Tips: Ange vilken enhet som ska anv\u00e4ndas n\u00e4r man skapar buffertar",selectGraphicLocationSymbol:"Adress- eller platssymbol",graphicLocationSymbolHintText:"Tips: Symbol f\u00f6r adresser som anv\u00e4ndarna s\u00f6kt efter eller platser som de klickat p\u00e5",fontColorLabel:"V\u00e4lj teckensnittsf\u00e4rg i s\u00f6kresultaten",fontColorHintText:"Tips: Teckensnittsf\u00e4rg i s\u00f6kresultaten",zoomToSelectedFeature:"Zooma till det valda geoobjektet",
zoomToSelectedFeatureHintText:"Tips: Zooma till det valda geoobjektet i st\u00e4llet f\u00f6r till bufferten",intersectSearchLocation:"Returnera korsande polygoner",intersectSearchLocationHintText:"Tips: Returnera polygoner som inneh\u00e5ller den efters\u00f6kta platsen snarare \u00e4n polygoner i bufferten",bufferVisibilityLabel:"Ange buffertens synlighet",bufferVisibilityHintText:"Tips: Bufferten kommer att visas p\u00e5 kartan",bufferColorLabel:"Ange buffertsymbol",bufferColorHintText:"Tips: V\u00e4lj f\u00e4rg och transparens f\u00f6r bufferten",
searchLayerResultLabel:"Rita bara resultat i det valda lagret",searchLayerResultHint:"Tips: Bara det valda lagret i s\u00f6kresultaten ritas upp p\u00e5 kartan"},layerSelector:{selectLayerLabel:"V\u00e4lj s\u00f6klager",layerSelectionHint:"Tips: Ange knappen Ange f\u00f6r att v\u00e4lja lager",addLayerButton:"Ange"},routeSetting:{routeSettingTabTitle:"Riktningsinst\u00e4llningar",routeServiceUrl:"Ruttj\u00e4nst",buttonSet:"Ange",routeServiceUrlHintText:"Tips: Klicka p\u00e5 \u00e2\u20ac\u02dcAnge\u00e2\u20ac\u2122 f\u00f6r att leta efter och v\u00e4lja en ruttj\u00e4nst",
directionLengthUnit:"L\u00e4ngdenheter f\u00f6r riktning",unitsForRouteHintText:"Tips: Anv\u00e4nds f\u00f6r att visa enheter f\u00f6r rutter",selectRouteSymbol:"V\u00e4lj symbol f\u00f6r visning av rutten",routeSymbolHintText:"Tips: Visade tidigare en linjesymbol f\u00f6r rutten",routingDisabledMsg:"Om du vill anv\u00e4nda rutter och v\u00e4gbeskrivningar m\u00e5ste du kontrollera att det har aktiverats i objektet ArcGIS Online."},networkServiceChooser:{arcgislabel:"L\u00e4gg till fr\u00e5n ArcGIS Online",
serviceURLabel:"L\u00e4gg till tj\u00e4nst-URL",routeURL:"Rutt-URL",validateRouteURL:"Validera",exampleText:"Exempel",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Ange en giltig ruttj\u00e4nst.",rateLimitExceeded:"Hastighetsbegr\u00e4nsningen \u00f6verskreds. F\u00f6rs\u00f6k igen senare.",errorInvokingService:"Anv\u00e4ndarnamn eller l\u00f6senord \u00e4r felaktigt."},
errorStrings:{bufferErrorString:"Ange ett giltigt numeriskt v\u00e4rde.",selectLayerErrorString:"V\u00e4lj vilka lager du vill s\u00f6ka i.",invalidDefaultValue:"Standardv\u00e4rdet f\u00f6r buffertavst\u00e5nd m\u00e5ste vara ifyllt. Ange buffertavst\u00e5ndet",invalidMaximumValue:"Maxv\u00e4rdet f\u00f6r buffertavst\u00e5nd m\u00e5ste vara ifyllt. Ange buffertavst\u00e5ndet",defaultValueLessThanMax:"Ange standardv\u00e4rdet f\u00f6r buffertavst\u00e5nd, och t\u00e4nk p\u00e5 att det inte f\u00e5r \u00f6verskrida maxgr\u00e4nsen",
defaultBufferValueGreaterThanZero:"Ange ett standardv\u00e4rde f\u00f6r buffertavst\u00e5ndet som \u00e4r st\u00f6rre \u00e4n noll",maximumBufferValueGreaterThanZero:"Ange ett maxv\u00e4rde f\u00f6r buffertavst\u00e5ndet som \u00e4r st\u00f6rre \u00e4n noll"},symbolPickerPreviewText:"F\u00f6rhandsgranska:",_localized:{}}});