// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miles",acronym:"mi"},kilometers:{displayText:"Kilom\u00e8tres",acronym:"km"},feet:{displayText:"Pieds",acronym:"pi"},meters:{displayText:"M\u00e8tres",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Param\u00e8tres de recherche",defaultBufferDistanceLabel:"D\u00e9finir la distance par d\u00e9faut de la zone tampon",maxBufferDistanceLabel:"D\u00e9finir la distance maximum de la zone tampon",bufferDistanceUnitLabel:"Unit\u00e9s de distance de la zone tampon",
defaultBufferHintLabel:"Astuce\u00a0: d\u00e9finissez la valeur par d\u00e9faut du curseur de la zone tampon",maxBufferHintLabel:"Astuce\u00a0: d\u00e9finissez la valeur maximum du curseur de la zone tampon",bufferUnitLabel:"Astuce\u00a0: d\u00e9finissez l\u2019unit\u00e9 pour cr\u00e9er la zone tampon",selectGraphicLocationSymbol:"Symbole d\u2019adresse ou d\u2019emplacement",graphicLocationSymbolHintText:"Astuce\u00a0: symbole d\u2019une adresse recherch\u00e9e ou d\u2019un emplacement s\u00e9lectionn\u00e9",
fontColorLabel:"S\u00e9lectionner la couleur de police pour les r\u00e9sultats de la recherche",fontColorHintText:"Astuce\u00a0: couleur de police des r\u00e9sultats de la recherche",zoomToSelectedFeature:"Zoom sur l'entit\u00e9 s\u00e9lectionn\u00e9e",zoomToSelectedFeatureHintText:"Astuce\u00a0: zoomez sur l'entit\u00e9 s\u00e9lectionn\u00e9e au lieu de la zone tampon",intersectSearchLocation:"Revenir aux polygones d'intersection",intersectSearchLocationHintText:"Astuce\u00a0: renvoyez les polygones contenant l'emplacement recherch\u00e9 au lieu des polygones au sein de la zone tampon",
bufferVisibilityLabel:"D\u00e9finir la visibilit\u00e9 de la zone tampon",bufferVisibilityHintText:"Astuce\u00a0: la zone tampon s'affichera sur la carte",bufferColorLabel:"D\u00e9finir le symbole de la zone tampon",bufferColorHintText:"Astuce\u00a0: s\u00e9lectionnez la couleur et la transparence de la zone tampon",searchLayerResultLabel:"Dessiner uniquement les r\u00e9sultats de la couche s\u00e9lectionn\u00e9e",searchLayerResultHint:"Astuce\u00a0: seule la couche s\u00e9lectionn\u00e9e dans les r\u00e9sultats de recherche s'affichera sur la carte."},
layerSelector:{selectLayerLabel:"S\u00e9lectionner des couches de recherche",layerSelectionHint:"Astuce\u00a0: utilisez le bouton D\u00e9finir pour s\u00e9lectionner les couches",addLayerButton:"D\u00e9finir"},routeSetting:{routeSettingTabTitle:"Attributs de direction",routeServiceUrl:"Service de calcul d'itin\u00e9raire",buttonSet:"D\u00e9finir",routeServiceUrlHintText:"Astuce\u00a0: cliquez sur D\u00e9finir pour rechercher et s\u00e9lectionner un service de calcul d'itin\u00e9raire",directionLengthUnit:"Unit\u00e9s de longueur de la direction",
unitsForRouteHintText:"Astuce\u00a0: utilis\u00e9 pour afficher les unit\u00e9s de l\u2019itin\u00e9raire",selectRouteSymbol:"S\u00e9lectionner le symbole pour afficher l\u2019itin\u00e9raire",routeSymbolHintText:"Astuce\u00a0: utilis\u00e9 pour afficher le symbole lin\u00e9aire de l\u2019itin\u00e9raire",routingDisabledMsg:"Pour activer les directions, assurez-vous que le calcul d\u2019itin\u00e9raire est activ\u00e9 dans l\u2019\u00e9l\u00e9ment ArcGIS\u00a0Online."},networkServiceChooser:{arcgislabel:"Ajouter depuis ArcGIS Online",
serviceURLabel:"Ajouter une URL de service",routeURL:"URL de l\u2019itin\u00e9raire",validateRouteURL:"Valider",exampleText:"Exemple",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Sp\u00e9cifiez un service d\u2019itin\u00e9raire valide.",rateLimitExceeded:"Limite de d\u00e9bit atteinte. R\u00e9essayez ult\u00e9rieurement.",errorInvokingService:"Le nom d'utilisateur ou le mot de passe est incorrect."},
errorStrings:{bufferErrorString:"Saisissez une valeur num\u00e9rique valide.",selectLayerErrorString:"S\u00e9lectionnez les couches \u00e0 rechercher.",invalidDefaultValue:"La distance de la zone tampon par d\u00e9faut ne peut pas \u00eatre vide. Veuillez sp\u00e9cifier la distance de la zone tampon.",invalidMaximumValue:"La distance de la zone tampon maximale ne peut pas \u00eatre vide. Veuillez sp\u00e9cifier la distance de la zone tampon.",defaultValueLessThanMax:"Sp\u00e9cifiez la distance de la zone tampon par d\u00e9faut au sein de la limite maximale",
defaultBufferValueGreaterThanZero:"Sp\u00e9cifiez une distance de la zone tampon par d\u00e9faut sup\u00e9rieure \u00e0\u00a00",maximumBufferValueGreaterThanZero:"Sp\u00e9cifiez une distance de la zone tampon maximale sup\u00e9rieure \u00e0\u00a00"},symbolPickerPreviewText:"Aper\u00e7u :",_localized:{}}});