// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miglia",acronym:"mi"},kilometers:{displayText:"Chilometri",acronym:"km"},feet:{displayText:"Piedi",acronym:"piedi"},meters:{displayText:"Metri",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Impostazione di ricerca",defaultBufferDistanceLabel:"Imposta distanza di buffer predefinita",maxBufferDistanceLabel:"Imposta distanza di buffer massima",bufferDistanceUnitLabel:"Unit\u00e0 distanza di buffer",defaultBufferHintLabel:"Suggerimento: impostare il valore predefinito per il cursore buffer",
maxBufferHintLabel:"Suggerimento: impostare il valore massimo per il cursore buffer",bufferUnitLabel:"Suggerimento: definire unit\u00e0 di creazione buffer",selectGraphicLocationSymbol:"Simbolo indirizzo o posizione",graphicLocationSymbolHintText:"Suggerimento: simbolo per l'indirizzo ricercato o la posizione selezionata",fontColorLabel:"Seleziona colore font per risultati della ricerca",fontColorHintText:"Suggerimento: colore font dei risultati della ricerca",zoomToSelectedFeature:"Zoom alla feature selezionata",
zoomToSelectedFeatureHintText:"Suggerimento: esegue lo zoom alla feature selezionata anzich\u00e9 al buffer",intersectSearchLocation:"Restituisci poligono o poligoni di intersezione",intersectSearchLocationHintText:"Suggerimento: restituisce il poligono o i poligoni contenenti la posizione ricercata anzich\u00e9 i poligoni all'interno del buffer",bufferVisibilityLabel:"Imposta visibilit\u00e0 buffer",bufferVisibilityHintText:"Suggerimento: il buffer verr\u00e0 visualizzato sulla mappa",bufferColorLabel:"Imposta simbolo buffer",
bufferColorHintText:"Suggerimento: selezionare colore e trasparenza del buffer",searchLayerResultLabel:"Disegna solo risultati del layer selezionato",searchLayerResultHint:"Suggerimento: solo il layer selezionato nei risultati della ricerca verr\u00e0 disegnato sulla mappa"},layerSelector:{selectLayerLabel:"Seleziona layer di ricerca",layerSelectionHint:"Suggerimento: utilizzare il pulsante di impostazione per selezionare layer",addLayerButton:"Imposta"},routeSetting:{routeSettingTabTitle:"Impostazioni direzioni",
routeServiceUrl:"Servizio itinerario",buttonSet:"Imposta",routeServiceUrlHintText:"Suggerimento: fare clic su \u00e2\u20ac\u02dcImposta\u00e2\u20ac\u2122 per individuare e selezionare un servizio itinerario",directionLengthUnit:"Unit\u00e0 di lunghezza direzione",unitsForRouteHintText:"Suggerimento: utilizzato per visualizzare unit\u00e0 per percorso",selectRouteSymbol:"Seleziona simbolo per visualizzare percorso",routeSymbolHintText:"Suggerimento: utilizzato per visualizzare simbolo linea del percorso",
routingDisabledMsg:"Per abilitare le direzioni accertarsi che gli itinerari siano abilitati nell'elemento di ArcGIS Online."},networkServiceChooser:{arcgislabel:"Aggiungi da ArcGIS Online",serviceURLabel:"Aggiungi URL del servizio",routeURL:"URL itinerario",validateRouteURL:"Convalida",exampleText:"Esempio",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Specificare un servizio Itinerari valido.",
rateLimitExceeded:"Superato limite velocit\u00e0. Riprovare pi\u00f9 tardi.",errorInvokingService:"Nome utente o password errati."},errorStrings:{bufferErrorString:"Immettere valore numerico valido.",selectLayerErrorString:"Selezionare i layer da cercare.",invalidDefaultValue:"La distanza di buffer predefinita non pu\u00f2 essere vuota. Specificare la distanza di buffer",invalidMaximumValue:"La distanza di buffer massima non pu\u00f2 essere vuota. Specificare la distanza di buffer",defaultValueLessThanMax:"Specificare la distanza di buffer predefinita all'interno del limite massimo",
defaultBufferValueGreaterThanZero:"Specificare la distanza di buffer predefinita maggiore di 0",maximumBufferValueGreaterThanZero:"Specificare la distanza di buffer massima maggiore di 0"},symbolPickerPreviewText:"Anteprima:",_localized:{}}});