// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Mailia",acronym:"mailia"},kilometers:{displayText:"Kilometri\u00e4",acronym:"km"},feet:{displayText:"Jalkaa",acronym:"ft"},meters:{displayText:"Metri\u00e4",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Hakuasetukset",defaultBufferDistanceLabel:"M\u00e4\u00e4rit\u00e4 puskurin oletuset\u00e4isyys",maxBufferDistanceLabel:"M\u00e4\u00e4rit\u00e4 puskurin enimm\u00e4iset\u00e4isyys",bufferDistanceUnitLabel:"Puskurin et\u00e4isyysyksik\u00f6t",
defaultBufferHintLabel:"Vihje: m\u00e4\u00e4rit\u00e4 oletusarvo puskurin liukus\u00e4\u00e4timelle",maxBufferHintLabel:"Vihje: m\u00e4\u00e4rit\u00e4 enimm\u00e4isarvo puskurin liukus\u00e4\u00e4timelle",bufferUnitLabel:"Vihje: m\u00e4\u00e4ritt\u00e4\u00e4 puskurin luonnin yksik\u00f6n",selectGraphicLocationSymbol:"Osoitteen tai sijainnin symboli",graphicLocationSymbolHintText:"Vihje: haetun osoitteen tai napsautetun sijainnin symboli",fontColorLabel:"Valitse hakutulosten fontin v\u00e4ri",fontColorHintText:"Vihje: hakutulosten fontin v\u00e4ri",
zoomToSelectedFeature:"Tarkenna valittuun kohteeseen",zoomToSelectedFeatureHintText:"Vihje: zoomaa valittuun kohteeseen puskurin sijaan",intersectSearchLocation:"Palauta leikkaavat aluekohteet",intersectSearchLocationHintText:"Vihje: palauta aluekohteet, jotka sis\u00e4lt\u00e4v\u00e4t haetun sijainnin puskurissa olevien aluekohteiden sijaan",bufferVisibilityLabel:"M\u00e4\u00e4rit\u00e4 puskurin n\u00e4kyvyys",bufferVisibilityHintText:"Vihje: puskuri n\u00e4ytet\u00e4\u00e4n kartalla",bufferColorLabel:"M\u00e4\u00e4rit\u00e4 puskurin symboli",
bufferColorHintText:"Vihje: valitse puskurin v\u00e4ri ja l\u00e4pin\u00e4kyvyys",searchLayerResultLabel:"Piirr\u00e4 vain valitut karttatason tulokset",searchLayerResultHint:"Vihje: kartalle piirret\u00e4\u00e4n vain valittu hakutulosten karttataso"},layerSelector:{selectLayerLabel:"Valitse hakukarttataso(t)",layerSelectionHint:"Vihje: k\u00e4yt\u00e4 M\u00e4\u00e4rit\u00e4-painiketta karttatasojen valintaan",addLayerButton:"Aseta"},routeSetting:{routeSettingTabTitle:"Suuntien asetukset",routeServiceUrl:"Reitityspalvelu",
buttonSet:"Aseta",routeServiceUrlHintText:"Vihje: selaa valitsemalla \u00e2\u20ac\u02dcAseta\u00e2\u20ac\u2122 ja valitse reitityspalvelu",directionLengthUnit:"Ajo-ohjeiden pituusyksik\u00f6t",unitsForRouteHintText:"Vihje: k\u00e4ytet\u00e4\u00e4n reitin yksik\u00f6iden n\u00e4ytt\u00e4miseen",selectRouteSymbol:"Valitse reitin n\u00e4ytt\u00e4miseen k\u00e4ytett\u00e4v\u00e4 symboli",routeSymbolHintText:"Vihje: k\u00e4ytet\u00e4\u00e4n viivasymbolin n\u00e4ytt\u00e4miseen reitiss\u00e4",routingDisabledMsg:"Jos haluat ottaa ajo-ohjeet k\u00e4ytt\u00f6\u00f6n, varmista, ett\u00e4 reititys on k\u00e4yt\u00f6ss\u00e4 ArcGIS Online -kohteessa."},
networkServiceChooser:{arcgislabel:"Lis\u00e4\u00e4 ArcGIS Online -palvelusta",serviceURLabel:"Lis\u00e4\u00e4 palvelun URL-osoite",routeURL:"Reitin URL-osoite",validateRouteURL:"Vahvista",exampleText:"Esimerkki",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"M\u00e4\u00e4rit\u00e4 kelvollinen reittipalvelu.",rateLimitExceeded:"Nopeusrajoitus ylittyi. Yrit\u00e4 my\u00f6hemmin uudelleen.",
errorInvokingService:"K\u00e4ytt\u00e4j\u00e4nimi tai salasana on virheellinen."},errorStrings:{bufferErrorString:"Anna kelvollinen numeroarvo.",selectLayerErrorString:"Valitse haettavat karttatasot.",invalidDefaultValue:"Puskurin oletuset\u00e4isyys ei voi olla tyhj\u00e4. M\u00e4\u00e4rit\u00e4 puskurin et\u00e4isyys",invalidMaximumValue:"Puskurin enimm\u00e4iset\u00e4isyys ei voi olla tyhj\u00e4. M\u00e4\u00e4rit\u00e4 puskurin et\u00e4isyys",defaultValueLessThanMax:"M\u00e4\u00e4rit\u00e4 puskurin oletuset\u00e4isyys enimm\u00e4ism\u00e4\u00e4r\u00e4n rajoissa",
defaultBufferValueGreaterThanZero:"M\u00e4\u00e4rit\u00e4 nollaa suurempi puskurin oletuset\u00e4isyys",maximumBufferValueGreaterThanZero:"M\u00e4\u00e4rit\u00e4 nollaa suurempi puskurin enimm\u00e4iset\u00e4isyys"},symbolPickerPreviewText:"Esikatselu:",_localized:{}}});