// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miles",acronym:"mi"},kilometers:{displayText:"Kilometers",acronym:"km"},feet:{displayText:"Feet",acronym:"ft"},meters:{displayText:"Meters",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Search Settings",defaultBufferDistanceLabel:"Set default buffer distance",maxBufferDistanceLabel:"Set maximum buffer distance",bufferDistanceUnitLabel:"Buffer distance units",defaultBufferHintLabel:"Hint: Set default value for the buffer slider",
maxBufferHintLabel:"Hint: Set maximum value for the buffer slider",bufferUnitLabel:"Hint: Define unit for creating buffer",selectGraphicLocationSymbol:"Address or location symbol",graphicLocationSymbolHintText:"Hint: Symbol for searched address or clicked location",fontColorLabel:"Select font color for search results",fontColorHintText:"Hint: Font color of search results",zoomToSelectedFeature:"Zoom to the selected feature",zoomToSelectedFeatureHintText:"Hint: Zoom to the selected feature instead of the buffer",
intersectSearchLocation:"Return intersecting polygon(s)",intersectSearchLocationHintText:"Hint: Return polygon(s) containing the searched location rather than polygons within the buffer",bufferVisibilityLabel:"Set buffer visibility",bufferVisibilityHintText:"Hint: The buffer will be displayed on the map",bufferColorLabel:"Set buffer symbol",bufferColorHintText:"Hint: Select color and transparency of buffer",searchLayerResultLabel:"Only draw selected layer results",searchLayerResultHint:"Hint: Only the selected layer in the search results will draw on map"},
layerSelector:{selectLayerLabel:"Select search layer(s)",layerSelectionHint:"Hint: Use the set button to select layer(s)",addLayerButton:"Set"},routeSetting:{routeSettingTabTitle:"Directions Settings",routeServiceUrl:"Routing Service",buttonSet:"Set",routeServiceUrlHintText:"Hint: Click \u2018Set\u2019 to browse and select a routing service",directionLengthUnit:"Direction length units",unitsForRouteHintText:"Hint: Used to display units for route",selectRouteSymbol:"Select symbol to display route",
routeSymbolHintText:"Hint: Used to display line symbol of the route",routingDisabledMsg:"To enable directions ensure that routing is enabled in the ArcGIS Online item."},networkServiceChooser:{arcgislabel:"Add from ArcGIS Online",serviceURLabel:"Add Service URL",routeURL:"Route URL",validateRouteURL:"Validate",exampleText:"Example",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",
invalidRouteServiceURL:"Please specify a valid Route service.",rateLimitExceeded:"Rate limit exceeded. Please try again later.",errorInvokingService:"Username or password is incorrect."},errorStrings:{bufferErrorString:"Please enter valid numeric value.",selectLayerErrorString:"Please select layer(s) to search.",invalidDefaultValue:"Default  buffer distance cannot be blank. Please specify the buffer distance",invalidMaximumValue:"Maximum buffer distance cannot be blank. Please specify the buffer distance",
defaultValueLessThanMax:"Please specify the default buffer distance within the maximum limit",defaultBufferValueGreaterThanZero:"Please specify the default buffer distance greater than 0",maximumBufferValueGreaterThanZero:"Please specify the maximum buffer distance greater than 0"},symbolPickerPreviewText:"Preview:",_localized:{ar:1,cs:1,da:1,de:1,el:1,es:1,et:1,fi:1,fr:1,he:1,hr:1,it:1,ja:1,ko:1,lt:1,lv:1,nb:1,nl:1,pl:1,"pt-br":1,"pt-pt":1,ro:1,ru:1,sr:1,sv:1,th:1,tr:1,vi:1,"zh-cn":1,"zh-hk":1,"zh-tw":1}}});