// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Milje",acronym:"mi"},kilometers:{displayText:"Kilometri",acronym:"km"},feet:{displayText:"Stope",acronym:"ft"},meters:{displayText:"Metri",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Postavke pretra\u017eivanja",defaultBufferDistanceLabel:"Postavite zadanu udaljenost pojasa",maxBufferDistanceLabel:"Postavi maksimalnu udaljenost pojasa",bufferDistanceUnitLabel:"Jedinice veli\u010dine pojasa",defaultBufferHintLabel:"Podsjetnik: postavite zadanu vrijednost za kliza\u010d pojasa",
maxBufferHintLabel:"Podsjetnik: postavite maksimalnu vrijednost za kliza\u010d pojasa",bufferUnitLabel:"Podsjetnik: definirajte jedinicu za stvaranje pojasa",selectGraphicLocationSymbol:"Simbol adrese ili lokacije",graphicLocationSymbolHintText:"Podsjetnik: simbol za pretra\u017eenu adresu ili odabranu lokaciju",fontColorLabel:"Odaberite boju fonta za rezultate pretra\u017eivanja",fontColorHintText:"Podsjetnik: boja fonta za rezultate pretra\u017eivanja",zoomToSelectedFeature:"Uve\u0107aj odabrani geoobjekt",
zoomToSelectedFeatureHintText:"Podsjetnik: uve\u0107aj odabrani geoobjekt umjesto pojasa",intersectSearchLocation:"Vrati poligon(e) koji se sijeku",intersectSearchLocationHintText:"Podsjetnik: vratite poligon(e) koji sadr\u017ee tra\u017eene lokacije umjesto poligone unutar pojasa",bufferVisibilityLabel:"Postavi vidljivost pojasa",bufferVisibilityHintText:"Podsjetnik: pojas \u0107e se prikazati na karti",bufferColorLabel:"Postavi simbol pojasa",bufferColorHintText:"Podsjetnik: odaberite boju i prozirnost pojasa",
searchLayerResultLabel:"Nacrtaj samo rezultate odabranog sloja",searchLayerResultHint:"Podsjetnik: samo \u0107e se odabrani sloj u rezultatima pretra\u017eivanja nacrtati na karti"},layerSelector:{selectLayerLabel:"Odaberite sloj(eve) koji se mogu pretra\u017eivati",layerSelectionHint:"Podsjetnik: upotrijebite gumb za postavljanje sloja(eva) za odabir",addLayerButton:"Postavi"},routeSetting:{routeSettingTabTitle:"Postavke uputa za vo\u017enju",routeServiceUrl:"Usluga rutiranja",buttonSet:"Postavi",
routeServiceUrlHintText:"Podsjetnik: kliknite na \u00e2\u20ac\u02dcPostavi\u00e2\u20ac\u2122 kako biste pregledavali i odabrali uslugu rutiranja",directionLengthUnit:"Jedinice udaljenosti u uputama za vo\u017enju",unitsForRouteHintText:"Posjetnik: upotrebljava se za prikaz jedinica rute",selectRouteSymbol:"Odaberi simbol za prikaz rute",routeSymbolHintText:"Podsjetnik: upotrebljava se za prikaz linije rute",routingDisabledMsg:"Da biste omogu\u0107ili upute za vo\u017enju, provjerite je li rutiranje omogu\u0107eno u ArcGIS Onlineu."},
networkServiceChooser:{arcgislabel:"Dodaj iz ArcGIS Online",serviceURLabel:"Dodaj URL usluge",routeURL:"URL rute",validateRouteURL:"Provjera",exampleText:"Primjer",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Odredite va\u017ee\u0107u uslugu rutiranja.",rateLimitExceeded:"Prema\u0161eno ograni\u010denje ocjenjivanja. Poku\u0161ajte ponovno kasnije.",
errorInvokingService:"Korisni\u010dko ime ili lozinka nije ispravna."},errorStrings:{bufferErrorString:"Unesite valjanu broj\u010danu vrijednost.",selectLayerErrorString:"Odaberite sloj(eve) za pretra\u017eivanje.",invalidDefaultValue:"Zadana veli\u010dina pojasa ne mo\u017ee biti prazna. Odredite veli\u010dinu pojasa",invalidMaximumValue:"Maksimalna veli\u010dina pojasa ne mo\u017ee biti prazna. Odredite veli\u010dinu pojasa",defaultValueLessThanMax:"Odredite zadanu veli\u010dinu pojasa unutar maksimalnog ograni\u010denja",
defaultBufferValueGreaterThanZero:"Odredite zadanu veli\u010dinu pojasa ve\u0107u od 0",maximumBufferValueGreaterThanZero:"Odredite maksimalnu veli\u010dinu pojasa ve\u0107u od 0"},symbolPickerPreviewText:"Pretpregled:",_localized:{}}});