// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Mylios",acronym:"myl."},kilometers:{displayText:"Kilometrai",acronym:"km"},feet:{displayText:"P\u0117dos",acronym:"p\u0117dos"},meters:{displayText:"Metrai",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Paie\u0161kos nuostatos",defaultBufferDistanceLabel:"Nustatyti numatyt\u0105j\u0105 buferio atstumo reik\u0161m\u0119",maxBufferDistanceLabel:"Nustatyti maksimali\u0105 buferio atstumo reik\u0161m\u0119",bufferDistanceUnitLabel:"Buferio atstumo vienetai",
defaultBufferHintLabel:"U\u017euomina: nustatykite buferio slankiklio numatyt\u0105j\u0105 reik\u0161m\u0119",maxBufferHintLabel:"U\u017euomina: nustatykite buferio slankiklio maksimali\u0105 reik\u0161m\u0119",bufferUnitLabel:"Patarimas: nustatykite buferio k\u016brimo vienet\u0105",selectGraphicLocationSymbol:"Adreso arba vietos simbolis",graphicLocationSymbolHintText:"Patarimas: ie\u0161koto adreso arba spustel\u0117tos vietos simbolis",fontColorLabel:"Pasirinkti paie\u0161kos rezultat\u0173 \u0161rifto spalv\u0105",
fontColorHintText:"Patarimas: paie\u0161kos rezultat\u0173 \u0161rifto spalva",zoomToSelectedFeature:"Priartinti pasirinkt\u0105 element\u0105",zoomToSelectedFeatureHintText:"U\u017euomina: priartinkite prie pasirinkto elemento, o ne buferio",intersectSearchLocation:"Gr\u0105\u017einti susikertan\u010dius plotus",intersectSearchLocationHintText:"U\u017euomina: gr\u0105\u017eina plotus, kuriuose yra ie\u0161koma vieta, o ne plotus, esan\u010dius buferyje",bufferVisibilityLabel:"Nustayti buferio matomum\u0105",
bufferVisibilityHintText:"U\u017euomina: buferis bus rodomas \u017eem\u0117lapyje",bufferColorLabel:"Nustatyti buferio simbol\u012f",bufferColorHintText:"U\u017euomina: pasirinkite buferio spalv\u0105 ir skaidrum\u0105",searchLayerResultLabel:"Nubr\u0117\u017eti tik pasirinkto sluoksnio rezultatus",searchLayerResultHint:"U\u017euomina: \u017eem\u0117lapyje bus vaizduojami tik pasirinkto sluoksnio paie\u0161kos rezultatai"},layerSelector:{selectLayerLabel:"Pasirinkti paie\u0161kos sluoksn\u012f (-ius)",
layerSelectionHint:"Patarimas: sluoksniui (-iams) pasirinkti naudokite nustatymo mygtuk\u0105",addLayerButton:"Grup\u0117"},routeSetting:{routeSettingTabTitle:"Kryp\u010di\u0173 nustatymai",routeServiceUrl:"Mar\u0161ruto paslauga",buttonSet:"Grup\u0117",routeServiceUrlHintText:"U\u017euomina: nor\u0117dami rasti ir pasirinkti mar\u0161rut\u0173 paslaug\u0105, spustel\u0117kite Nustatyti",directionLengthUnit:"Krypties ilgio vienetai",unitsForRouteHintText:"Patarimas: naudojama mar\u0161ruto vienetams rodyti",
selectRouteSymbol:"Pasirinkti mar\u0161ruto rodymo simbol\u012f",routeSymbolHintText:"Patarimas: naudojamas mar\u0161ruto linijos simboliui rodyti",routingDisabledMsg:"Jei norite \u012fjungti nuorodas, \u012fsitikinkite, kad mar\u0161rutas \u012fjungtas ArcGIS Online elemente."},networkServiceChooser:{arcgislabel:"Prid\u0117ti i\u0161 ArcGIS Online",serviceURLabel:"Prid\u0117ti paslaugos URL",routeURL:"Mar\u0161ruto URL",validateRouteURL:"Tikrinti",exampleText:"Pavyzdys",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",
hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Nurodykite galiojan\u010di\u0105 mar\u0161ruto paslaug\u0105.",rateLimitExceeded:"Vir\u0161ytas apribojimo limitas. Pabandykite dar kart\u0105 v\u0117liau.",errorInvokingService:"Vartotojo vardas arba slapta\u017eodis neteisingas."},errorStrings:{bufferErrorString:"\u012eveskite leistin\u0105 skaitin\u0119 reik\u0161m\u0119.",selectLayerErrorString:"Pasirinkite ie\u0161kos sluoksn\u012f (-ius)",
invalidDefaultValue:"Numatytasis buferio atstumas negali b\u016bti tu\u0161\u010dias. Nurodykite buferio atstum\u0105",invalidMaximumValue:"Maksimalus buferio atstumas negali b\u016bti tu\u0161\u010dias. Nurodykite buferio atstum\u0105",defaultValueLessThanMax:"Nurodykite numatyt\u0105j\u012f buferio atstum\u0105 maksimaliose ribose",defaultBufferValueGreaterThanZero:"Nurodykite numatyt\u0105j\u012f buferio atstum\u0105 didesn\u012f u\u017e 0",maximumBufferValueGreaterThanZero:"Nurodykite maksimal\u0173 buferio atstum\u0105 didesn\u012f u\u017e 0"},
symbolPickerPreviewText:"Per\u017ei\u016bra:",_localized:{}}});