// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Miili",acronym:"mi"},kilometers:{displayText:"Kilomeetrit",acronym:"m"},feet:{displayText:"Jalga",acronym:"jl"},meters:{displayText:"Meetrit",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Otsingu seaded",defaultBufferDistanceLabel:"M\u00e4\u00e4ra puhvri\u00a0vaikeulatus",maxBufferDistanceLabel:"M\u00e4\u00e4ra puhvri maksimumulatus",bufferDistanceUnitLabel:"Puhvri ulatuse \u00fchikud",defaultBufferHintLabel:"Vihje: m\u00e4\u00e4rake puhvri liuguri vaikev\u00e4\u00e4rtus",
maxBufferHintLabel:"Vihje: m\u00e4\u00e4rake puhvri liuguri maksimumv\u00e4\u00e4rtus",bufferUnitLabel:"Vihje: m\u00e4\u00e4ratlege puhvri loomise \u00fchik",selectGraphicLocationSymbol:"Aadressi v\u00f5i asukoha s\u00fcmbol",graphicLocationSymbolHintText:"Vihje: otsitud aadressi v\u00f5i kl\u00f5psatud asukoha s\u00fcmbol",fontColorLabel:"Vali otsingutulemuste fondi v\u00e4rv",fontColorHintText:"Vihje: otsingutulemuste fondi v\u00e4rv",zoomToSelectedFeature:"Suumi valitud objektile",zoomToSelectedFeatureHintText:"Vihje: suumige puhvri asemel valitud objektile",
intersectSearchLocation:"Tagasta l\u00f5ikuvad pol\u00fcgoonid",intersectSearchLocationHintText:"Vihje:\u00a0puhvris asuvate pol\u00fcgoonide asemel tagastatakse otsitud asukohta sisaldavad\u00a0pol\u00fcgoonid",bufferVisibilityLabel:"M\u00e4\u00e4ra puhvri n\u00e4htavus",bufferVisibilityHintText:"Vihje: puhver kuvatakse kaardil",bufferColorLabel:"M\u00e4\u00e4ra puhvri s\u00fcmbol",bufferColorHintText:"Vihje: valige puhvri v\u00e4rv ja l\u00e4bipaistvus",searchLayerResultLabel:"Joonista ainult valitud kihi tulemused",
searchLayerResultHint:"Vihje: kaardile joonistatakse ainult otsingutulemustes valitud kiht"},layerSelector:{selectLayerLabel:"Vali otsingukiht (-kihid)",layerSelectionHint:"Vihje: kasutage kihi (kihtide) valimiseks nuppu M\u00e4\u00e4ra",addLayerButton:"M\u00e4\u00e4ra"},routeSetting:{routeSettingTabTitle:"Teejuhiste seaded",routeServiceUrl:"Marsruutimisteenus",buttonSet:"M\u00e4\u00e4ra",routeServiceUrlHintText:"Vihje:\u00a0kl\u00f5psake teekonnajuhiste teenuse sirvimiseks ja valimiseks k\u00e4sku \u00e2\u20ac\u02dcM\u00e4\u00e4ra\u00e2\u20ac\u2122.",
directionLengthUnit:"Teejuhise pikkus\u00fchikud",unitsForRouteHintText:"Vihje: kasutatakse marsruudi \u00fchikute kuvamiseks",selectRouteSymbol:"Vali marsruudi kuvamiseks s\u00fcmbol",routeSymbolHintText:"Vihje: kasutatakse marsruudi joons\u00fcmboli kuvamiseks",routingDisabledMsg:"Enne teejuhiste lubamist\u00a0veenduge, et marsruutimine on\u00a0ArcGIS Online'i \u00fcksuses lubatud."},networkServiceChooser:{arcgislabel:"Lisa ArcGIS Online\u2019ist",serviceURLabel:"Lisa teenuse URL",routeURL:"Marsruudi URL",
validateRouteURL:"Valideeri",exampleText:"N\u00e4ide",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"M\u00e4\u00e4rake sobiv marsruuditeenus.",rateLimitExceeded:"Liikluse piirm\u00e4\u00e4r on \u00fcletatud. Proovige hiljem uuesti.",errorInvokingService:"Kasutajanimi v\u00f5i parool on vale."},errorStrings:{bufferErrorString:"Sisestage sobiv numbriline v\u00e4\u00e4rtus.",
selectLayerErrorString:"Valige otsingukiht (-kihid).",invalidDefaultValue:"Puhvri vaikeulatuse v\u00e4li ei tohi olla t\u00fchi. M\u00e4\u00e4rake puhvri ulatus",invalidMaximumValue:"Puhvri maksimumulatuse v\u00e4li ei tohi olla t\u00fchi. M\u00e4\u00e4rake puhvri ulatus",defaultValueLessThanMax:"M\u00e4\u00e4rake puhvri vaikeulatus limiidi piires",defaultBufferValueGreaterThanZero:"M\u00e4\u00e4rake puhvri vaikeulatus, mis on suurem kui 0",maximumBufferValueGreaterThanZero:"M\u00e4\u00e4rake puhvri maksimumulatus, mis on suurem kui 0"},
symbolPickerPreviewText:"Eelvaade:",_localized:{}}});