// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Milhas",acronym:"mi"},kilometers:{displayText:"Quil\u00f4metros",acronym:"km"},feet:{displayText:"P\u00e9s",acronym:"p\u00e9s"},meters:{displayText:"Metros",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Configura\u00e7\u00f5es da Pesquisa",defaultBufferDistanceLabel:"Configurar dist\u00e2ncia de buffer padr\u00e3o",maxBufferDistanceLabel:"Configurar dist\u00e2ncia m\u00e1xima de buffer",bufferDistanceUnitLabel:"Unidades de dist\u00e2ncia do buffer",
defaultBufferHintLabel:"Sugest\u00e3o: Configurar valor padr\u00e3o para controle deslizante de buffer",maxBufferHintLabel:"Sugest\u00e3o: Configurar valor m\u00e1ximo para controle deslizante de buffer",bufferUnitLabel:"Sugest\u00e3o: Defina a unidade para criar buffer",selectGraphicLocationSymbol:"S\u00edmbolo de local ou endere\u00e7o",graphicLocationSymbolHintText:"Sugest\u00e3o: S\u00edmbolo para endere\u00e7o pesquisado ou local clicado",fontColorLabel:"Selecionar cor da fonte para resultados da pesquisa",
fontColorHintText:"Sugest\u00e3o: Cor da fonte de resultados da pesquisa",zoomToSelectedFeature:"Zoom para fei\u00e7\u00e3o selecionada",zoomToSelectedFeatureHintText:"Sugest\u00e3o: Ampliar na fei\u00e7\u00e3o selecionada, ao inv\u00e9s do buffer",intersectSearchLocation:"Retornar pol\u00edgonos de intersec\u00e7\u00e3o",intersectSearchLocationHintText:"Sugest\u00e3o: Retorne pol\u00edgonos contendo o local pesquisado, ao inv\u00e9s de pol\u00edgonos dentro do buffer",bufferVisibilityLabel:"Configurar visibilidade do buffer",
bufferVisibilityHintText:"Sugest\u00e3o: O buffer ser\u00e1 exibido no mapa",bufferColorLabel:"Configurar s\u00edmbolo do buffer",bufferColorHintText:"Sugest\u00e3o: Selecione cor e transpar\u00eancia do buffer",searchLayerResultLabel:"Desenhar somente resultados da camada selecionada",searchLayerResultHint:"Sugest\u00e3o: Somente a camada selecionada nos resultados da pesquisa desenhar\u00e1 no mapa"},layerSelector:{selectLayerLabel:"Selecionar camadas de pesquisa",layerSelectionHint:"Sugest\u00e3o: Utilize o bot\u00e3o configurar para selecionar camadas",
addLayerButton:"Configurar"},routeSetting:{routeSettingTabTitle:"Configura\u00e7\u00f5es de Dire\u00e7\u00f5es",routeServiceUrl:"Servi\u00e7o de Rota",buttonSet:"Configurar",routeServiceUrlHintText:"Sugest\u00e3o: Clique em \u00e2\u20ac\u02dcSet\u00e2\u20ac\u2122 para procurar e selecionar um servi\u00e7o de rota",directionLengthUnit:"Unidades do comprimento de dire\u00e7\u00e3o",unitsForRouteHintText:"Sugest\u00e3o: Utilizado para exibir unidades para rota",selectRouteSymbol:"Selecionar s\u00edmbolo para exibir rota",
routeSymbolHintText:"Sugest\u00e3o: Utilizado para exibir s\u00edmbolo de linha da rota",routingDisabledMsg:"Para habilitar dire\u00e7\u00f5es, garanta que a rota esteja habilitada no item do ArcGIS Online."},networkServiceChooser:{arcgislabel:"Adicionar do ArcGIS Online",serviceURLabel:"Adicionar URL de Servi\u00e7o",routeURL:"URL da Rota",validateRouteURL:"Validar",exampleText:"Exemplo",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",
invalidRouteServiceURL:"Especifique um servi\u00e7o de Rota v\u00e1lido.",rateLimitExceeded:"Limite de taxa excedido. Tente novamente mais tarde.",errorInvokingService:"O nome de usu\u00e1rio ou senha est\u00e1 incorreta."},errorStrings:{bufferErrorString:"Inisra um valor num\u00e9rico v\u00e1lido.",selectLayerErrorString:"Selecione as camadas para pesquisar.",invalidDefaultValue:"A dist\u00e2ncia de buffer padr\u00e3o n\u00e3o pode estar em branco. Especifique a dist\u00e2ncia de buffer",invalidMaximumValue:"A dist\u00e2ncia de buffer m\u00e1xima n\u00e3o pode estar em branco. Especifique a dist\u00e2ncia de buffer",
defaultValueLessThanMax:"Especifique a dist\u00e2ncia de buffer padr\u00e3o dentro do limite m\u00e1ximo",defaultBufferValueGreaterThanZero:"Especifique a dist\u00e2ncia de buffer padr\u00e3o maior que 0",maximumBufferValueGreaterThanZero:"Especifique a dist\u00e2ncia de buffer m\u00e1xima maior que 0"},symbolPickerPreviewText:"Visualizar:",_localized:{}}});