// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Milje",acronym:"mi"},kilometers:{displayText:"Kilometri",acronym:"km"},feet:{displayText:"Stope",acronym:"ft"},meters:{displayText:"Metri",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Postavke pretrage",defaultBufferDistanceLabel:"Postavi podrazumevano rastojanje zone bliskosti",maxBufferDistanceLabel:"Postavi maksimalno rastojanje zone bliskosti",bufferDistanceUnitLabel:"Jedinice rastojanja zone bliskosti",defaultBufferHintLabel:"Napomena: postavite podrazumevanu vrednost za kliza\u010d zone bliskosti",
maxBufferHintLabel:"Napomena: postavite maksimalnu vrednost za kliza\u010d zone bliskosti",bufferUnitLabel:"Napomena: defini\u0161ite jedinicu za kreiranje zone bliskosti",selectGraphicLocationSymbol:"Simbol adresa ili lokacije",graphicLocationSymbolHintText:"Napomena: Simbol za tra\u017eenu adresu ili lokaciju na koju je kliknuto",fontColorLabel:"Izaberite boju fonta za rezultate pretrage",fontColorHintText:"Napomena: boja fonta za rezultate pretrage",zoomToSelectedFeature:"Zumiraj do izabranog geooobjekta",
zoomToSelectedFeatureHintText:"Napomena: zumirajte do izabranog geoobjekta umesto zone bliskosti",intersectSearchLocation:"Vrati poligon(e) koji se seku",intersectSearchLocationHintText:"Napomena: vratite poligon(e) koji sadr\u017ei(e) tra\u017eenu lokaciju, pre poligona u okviru zone bliskosti",bufferVisibilityLabel:"Podesi vidljivost zone bliskosti",bufferVisibilityHintText:"Napomena: zona bliskosti \u0107e biti prikazana na mapi",bufferColorLabel:"Podesi simbol zone bliskosti",bufferColorHintText:"Napomena: izaberite boju i prozirnost zone bliskosti",
searchLayerResultLabel:"Nacrtaj samo rezultate izabranog sloja",searchLayerResultHint:"Napomena: samo izabrani sloj u rezultatima pretrage \u0107e se iscrtati na mapi"},layerSelector:{selectLayerLabel:"Izaberite sloj(eve) pretrage",layerSelectionHint:"Napomena: koristite dugme postavke da biste izabrali sloj(eve)",addLayerButton:"Postavi"},routeSetting:{routeSettingTabTitle:"Postavke smernica",routeServiceUrl:"Servis za rutiranje",buttonSet:"Postavi",routeServiceUrlHintText:"Napomena: kliknite na \u00e2\u20ac\u02dcPostavi\u00e2\u20ac\u2122 da biste potra\u017eili i izabrali servis za rutiranje",
directionLengthUnit:"Jedinice du\u017eine pravca",unitsForRouteHintText:"Napomena: koristi se za prikazivanje jedinica za rutiranje",selectRouteSymbol:"Izaberite simbol za prikaz rute",routeSymbolHintText:"Napomena: koristi se za prikaz simbola linije rute",routingDisabledMsg:"Da biste omogu\u0107ili uputstva za navigaciju postarajte se da je rutiranje omogu\u0107eno u stavci ArcGIS Online."},networkServiceChooser:{arcgislabel:"Dodaj iz ArcGIS Online",serviceURLabel:"Dodaj URL adresu servisa",routeURL:"URL adresa rutiranja",
validateRouteURL:"Proveri valjanost",exampleText:"Primer",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Navedite va\u017ee\u0107i servis za rutiranje.",rateLimitExceeded:"Prekora\u010deno je ograni\u010denje stope. Poku\u0161ajte ponovo kasnije.",errorInvokingService:"Korisni\u010dko ime ili lozinka su neva\u017ee\u0107i."},errorStrings:{bufferErrorString:"Unesite va\u017ee\u0107u numeri\u010dku vrednost.",
selectLayerErrorString:"Izaberite sloj(eve) za pretragu.",invalidDefaultValue:"Podrazumevano rastojanje zone bliskosti ne mo\u017ee da bude prazno. Navedite rastojanje zone bliskosti",invalidMaximumValue:"Maksimalno rstojanje zone bliskosti ne mo\u017ee da bude prazno. Navedite rastojanje zone bliskosti",defaultValueLessThanMax:"Navedite podrazumevano rastojanje zone bliskosti unutar maksimalnog ograni\u010denja",defaultBufferValueGreaterThanZero:"Navedite podrazumevano rastojanje zone bliskosti ve\u0107e od 0",
maximumBufferValueGreaterThanZero:"Navedite maksimalno rastojanje zone bliskosti ve\u0107e od 0"},symbolPickerPreviewText:"Pregledaj:",_localized:{}}});