// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Meilen",acronym:"mi"},kilometers:{displayText:"Kilometer",acronym:"km"},feet:{displayText:"Fu\u00df",acronym:"ft"},meters:{displayText:"Meter",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Sucheinstellungen",defaultBufferDistanceLabel:"Standardpufferabstand festlegen",maxBufferDistanceLabel:"Maximalen Pufferabstand festlegen",bufferDistanceUnitLabel:"Pufferabstandseinheiten",defaultBufferHintLabel:"Hinweis: Standardwert f\u00fcr den Pufferschieberegler festlegen",
maxBufferHintLabel:"Hinweis: Maximalwert f\u00fcr den Pufferschieberegler festlegen",bufferUnitLabel:"Hinweis: Definiert die Einheit f\u00fcr die Erstellung des Puffers",selectGraphicLocationSymbol:"Symbol f\u00fcr Adresse oder Position",graphicLocationSymbolHintText:"Hinweis: Symbol f\u00fcr gesuchte Adresse oder aktivierte Position",fontColorLabel:"Schriftfarbe f\u00fcr Suchergebnisse ausw\u00e4hlen",fontColorHintText:"Hinweis: Schriftfarbe f\u00fcr Suchergebnisse",zoomToSelectedFeature:"Auf das ausgew\u00e4hlte Feature zoomen",
zoomToSelectedFeatureHintText:"Hinweis: Zoomen Sie auf das ausgew\u00e4hlte Feature statt auf den Puffer.",intersectSearchLocation:"Sich schneidende(s) Polygon(e) zur\u00fcckgeben",intersectSearchLocationHintText:"Hinweis: Geben Sie Polygone zur\u00fcck, die die gesuchte Position enthalten, anstatt Polygone innerhalb des Puffers.",bufferVisibilityLabel:"Puffersichtbarkeit festlegen",bufferVisibilityHintText:"Hinweis: Der Puffer wird auf der Karte angezeigt.",bufferColorLabel:"Puffersymbol festlegen",
bufferColorHintText:"Hinweis: W\u00e4hlen Sie die Farbe und die Transparenz des Puffers aus.",searchLayerResultLabel:"Nur ausgew\u00e4hlte Layer-Ergebnisse darstellen",searchLayerResultHint:"Hinweis: Nur der ausgew\u00e4hlte Layer in den Suchergebnissen wird auf der Karte dargestellt."},layerSelector:{selectLayerLabel:"Such-Layer(s) ausw\u00e4hlen",layerSelectionHint:'Hinweis: Verwenden Sie die Schaltfl\u00e4che "Festlegen", um Layer auszuw\u00e4hlen',addLayerButton:"Festlegen"},routeSetting:{routeSettingTabTitle:"Wegbeschreibungseinstellungen",
routeServiceUrl:"Routing-Service",buttonSet:"Festlegen",routeServiceUrlHintText:'Hinweis: Klicken Sie auf "Festlegen", um einen Routing-Service zu durchsuchen und auszuw\u00e4hlen.',directionLengthUnit:"L\u00e4ngeneinheiten f\u00fcr Wegbeschreibung",unitsForRouteHintText:"Hinweis: Wird zum Anzeigen von Einheiten f\u00fcr die Route verwendet",selectRouteSymbol:"Symbol zum Anzeigen der Route ausw\u00e4hlen",routeSymbolHintText:"Hinweis: Wird zum Anzeigen des Liniensymbols der Route verwendet",routingDisabledMsg:"Um Wegbeschreibungen zu aktivieren, m\u00fcssen Sie sicherstellen, dass Routen im ArcGIS Online-Element aktiviert sind."},
networkServiceChooser:{arcgislabel:"Aus ArcGIS Online hinzuf\u00fcgen",serviceURLabel:"Service-URL hinzuf\u00fcgen",routeURL:"Routen-URL",validateRouteURL:"\u00dcberpr\u00fcfen",exampleText:"Beispiel",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Geben Sie einen g\u00fcltigen Routen-Service an.",rateLimitExceeded:"Daten\u00fcbertragungsrate \u00fcberschritten. Versuchen Sie es sp\u00e4ter erneut.",
errorInvokingService:"Falscher Benutzername oder falsches Kennwort."},errorStrings:{bufferErrorString:"Geben Sie einen g\u00fcltigen numerischen Wert ein.",selectLayerErrorString:"W\u00e4hlen Sie den/die zu durchsuchenden Layer aus.",invalidDefaultValue:"Der Standardpufferabstand darf nicht leer sein. Geben Sie den Pufferabstand an",invalidMaximumValue:"Der maximale Pufferabstand darf nicht leer sein. Geben Sie den Pufferabstand an",defaultValueLessThanMax:"Geben Sie den Standardpufferabstand innerhalb der maximalen Grenzwerte an",
defaultBufferValueGreaterThanZero:"Geben Sie f\u00fcr den Standardpufferabstand einen Wert gr\u00f6\u00dfer als 0 an",maximumBufferValueGreaterThanZero:"Geben Sie f\u00fcr den maximalen Pufferabstand einen Wert gr\u00f6\u00dfer als 0 an"},symbolPickerPreviewText:"Vorschau:",_localized:{}}});