// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Millas",acronym:"mi"},kilometers:{displayText:"Kil\u00f3metros",acronym:"km"},feet:{displayText:"Pies",acronym:"pie"},meters:{displayText:"Metros",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Configuraci\u00f3n de b\u00fasqueda",defaultBufferDistanceLabel:"Definir distancia de zona de influencia predeterminada",maxBufferDistanceLabel:"Definir distancia de zona de influencia m\u00e1xima",bufferDistanceUnitLabel:"Unidades de distancia del \u00e1rea de influencia",
defaultBufferHintLabel:"Sugerencia: defina el valor predeterminado para el control deslizante de zona de influencia",maxBufferHintLabel:"Sugerencia: defina el valor m\u00e1ximo para el control deslizante de zona de influencia",bufferUnitLabel:"Sugerencia: define una unidad para crear la zona de influencia",selectGraphicLocationSymbol:"S\u00edmbolo de direcci\u00f3n o ubicaci\u00f3n",graphicLocationSymbolHintText:"Sugerencia: s\u00edmbolo para la direcci\u00f3n buscada o para la ubicaci\u00f3n en la que se ha hecho clic",
fontColorLabel:"Seleccionar color de fuente para resultados de b\u00fasqueda",fontColorHintText:"Sugerencia: color de fuente de los resultados de la b\u00fasqueda",zoomToSelectedFeature:"Aplicar zoom a la entidad seleccionada",zoomToSelectedFeatureHintText:"Sugerencia: aplique el zoom a la entidad seleccionada en lugar de la zona de influencia",intersectSearchLocation:"Devolver pol\u00edgonos que se intersecan",intersectSearchLocationHintText:"Sugerencia: devuelva los pol\u00edgonos que contienen la ubicaci\u00f3n buscada en lugar de los pol\u00edgonos contenidos en la zona de influencia",
bufferVisibilityLabel:"Definir visibilidad de zona de influencia",bufferVisibilityHintText:"Sugerencia: la zona de influencia se mostrar\u00e1 en el mapa",bufferColorLabel:"Definir s\u00edmbolo de zona de influencia",bufferColorHintText:"Sugerencia: seleccione el color y la transparencia de la zona de influencia",searchLayerResultLabel:"Dibujar solo resultados de la capa seleccionada",searchLayerResultHint:"Sugerencia: solo la capa seleccionada en los resultados de b\u00fasqueda se dibujar\u00e1 en el mapa"},
layerSelector:{selectLayerLabel:"Seleccionar capas de b\u00fasqueda",layerSelectionHint:"Sugerencia: usa el bot\u00f3n de definir para seleccionar capas",addLayerButton:"Definir"},routeSetting:{routeSettingTabTitle:"Configuraciones de indicaciones",routeServiceUrl:"Servicio de generaci\u00f3n de rutas",buttonSet:"Definir",routeServiceUrlHintText:'Sugerencia: haga clic en "Definir" para examinar y seleccionar un servicio de generaci\u00f3n de rutas',directionLengthUnit:"Unidades de longitud de direcci\u00f3n",
unitsForRouteHintText:"Sugerencia: se utiliza para visualizar las unidades para la ruta",selectRouteSymbol:"Seleccionar s\u00edmbolo para visualizar ruta",routeSymbolHintText:"Sugerencia: se utiliza para visualizar el s\u00edmbolo de l\u00ednea de la ruta",routingDisabledMsg:"Para habilitar las indicaciones, aseg\u00farate de que la generaci\u00f3n de rutas est\u00e1 habilitada en el elemento de ArcGIS Online."},networkServiceChooser:{arcgislabel:"Agregar desde ArcGIS Online",serviceURLabel:"Agregar URL de servicio",
routeURL:"URL de ruta",validateRouteURL:"Validar",exampleText:"Ejemplo",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",invalidRouteServiceURL:"Especifica un servicio de rutas v\u00e1lido.",rateLimitExceeded:"Se ha superado el l\u00edmite de velocidad. Vuelva a intentarlo m\u00e1s tarde.",errorInvokingService:"El nombre de usuario o la contrase\u00f1a son incorrectos."},
errorStrings:{bufferErrorString:"Introduce un valor num\u00e9rico v\u00e1lido.",selectLayerErrorString:"Selecciona las capas para buscar.",invalidDefaultValue:"La distancia de zona de influencia predeterminada no puede estar en blanco. Especifica la distancia de zona de influencia.",invalidMaximumValue:"La distancia de zona de influencia m\u00e1xima no puede estar en blanco. Especifica la distancia de zona de influencia.",defaultValueLessThanMax:"Especifica la distancia de zona de influencia predeterminada dentro del l\u00edmite m\u00e1ximo",
defaultBufferValueGreaterThanZero:"Especifica una distancia de zona de influencia predeterminada mayor que 0",maximumBufferValueGreaterThanZero:"Especifica una distancia de zona de influencia m\u00e1xima mayor que 0"},symbolPickerPreviewText:"Vista previa:",_localized:{}}});