// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define({"widgets/NearMe/setting/nls/strings":{units:{miles:{displayText:"Milhas",acronym:"mi"},kilometers:{displayText:"Quil\u00f3metros",acronym:"km"},feet:{displayText:"P\u00e9s",acronym:"ft"},meters:{displayText:"Metros",acronym:"m"}},searchSetting:{searchSettingTabTitle:"Configura\u00e7\u00f5es da Pesquisa",defaultBufferDistanceLabel:"Definir dist\u00e2ncia predefinida do buffer",maxBufferDistanceLabel:"Definir dist\u00e2ncia m\u00e1xima do buffer",bufferDistanceUnitLabel:"Unidades de distancia buffer",
defaultBufferHintLabel:"Dica: Defina valor predefinido para o controlo deslizante de buffer",maxBufferHintLabel:"Dica: Definir valor m\u00e1ximo para o controlo deslizante de buffer",bufferUnitLabel:"Sugest\u00e3o: Definir unidade para cria\u00e7\u00e3o de buffer",selectGraphicLocationSymbol:"S\u00edmbolo de endere\u00e7o ou localiza\u00e7\u00e3o",graphicLocationSymbolHintText:"Sugest\u00e3o: S\u00edmbolo para endere\u00e7o pesquisado ou localiza\u00e7\u00e3o clicada",fontColorLabel:"Seleccionar cor de fonte para resultados de pesquisa",
fontColorHintText:"Sugest\u00e3o: Cor de fonte para resultados de pesquisa",zoomToSelectedFeature:"Aplique zoom ao elemento selecionado.",zoomToSelectedFeatureHintText:"Dica: Aplicar zoom ao elemento selecionado ao inv\u00e9s de aplicar ao buffer",intersectSearchLocation:"Apresente pol\u00edgono(s) em interce\u00e7\u00e3o",intersectSearchLocationHintText:"Dica: Apresentar pol\u00edgono(s) que cont\u00eam a localiza\u00e7\u00e3o pesquisada ao inv\u00e9s de pol\u00edgonos no interior do buffer",bufferVisibilityLabel:"Defina a visibilidade do buffer",
bufferVisibilityHintText:"Dica: O buffer ser\u00e1 exibido no mapa.",bufferColorLabel:"Defina o s\u00edmbolo do buffer",bufferColorHintText:"Dica: Selecione cor e transpar\u00eancia do buffer",searchLayerResultLabel:"Apenas representar resultados de camadas selecionadas",searchLayerResultHint:"Dica: Apenas a camada selecionada nos resultados de pesquisa ser\u00e1 representada no mapa"},layerSelector:{selectLayerLabel:"Camada(s) de pesquisa seleccionada",layerSelectionHint:"Sugest\u00e3o: Ise o bot\u00e3o de defini\u00e7\u00e3o para camada(s) seleccionadas",
addLayerButton:"Definir"},routeSetting:{routeSettingTabTitle:"Defini\u00e7\u00f5es de Dire\u00e7\u00e3o",routeServiceUrl:"Servi\u00e7o de Roteamento",buttonSet:"Definir",routeServiceUrlHintText:"Dica: Clique em \u00e2\u20ac\u02dcSet\u00e2\u20ac\u2122 para navegar e selecione um servi\u00e7o de rotas",directionLengthUnit:"Unidades de comprimento de direc\u00e7\u00e3o",unitsForRouteHintText:"Sugest\u00e3o: Usado para exibir unidade para roteamento",selectRouteSymbol:"Seleccionar s\u00edmbolo para exibir rota",
routeSymbolHintText:"Sugest\u00e3o: Usado para exibir s\u00edmbolo linha da rota",routingDisabledMsg:"Para permitir direc\u00e7\u00f5es certifique-se que o roteamento est\u00e1 activo no item ArcGIS Online."},networkServiceChooser:{arcgislabel:"Adicionar de ArcGIS Online",serviceURLabel:"Adicionar URL de Servi\u00e7o",routeURL:"URL de rota",validateRouteURL:"Validar",exampleText:"Exemplo",hintRouteURL1:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/",hintRouteURL2:"https://route.arcgis.com/arcgis/rest/services/World/Route/NAServer/Route_World",
invalidRouteServiceURL:"Por favor especifique o servi\u00e7o de Roteamento v\u00e1lido.",rateLimitExceeded:"Limite de classifica\u00e7\u00e3o ultrapassado. Por favor tente mais tarde.",errorInvokingService:"Nome de utilizador ou palavra-passe incorreto."},errorStrings:{bufferErrorString:"Por favor especifique um valor num\u00e9rico v\u00e1lido.",selectLayerErrorString:"Por favor seleccione camada(s) para pesquisar.",invalidDefaultValue:"A distancia buffer por omiss\u00e3o n\u00e3o pode estar em branco. Por favor especifique a distancia buffer",
invalidMaximumValue:"Distancia m\u00e1xima buffer n\u00e3o pode estar em branco. Por favor especifique a distancia buffer",defaultValueLessThanMax:"Por favor especifique a distancia buffer por omiss\u00e3o dentro do limite m\u00e1ximo",defaultBufferValueGreaterThanZero:"Por favor especifique a distancia buffer por omiss\u00e3o maior do que 0",maximumBufferValueGreaterThanZero:"Por favor especifique a distancia buffer m\u00e1xima maior do que 0"},symbolPickerPreviewText:"Visualizar:",_localized:{}}});