// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/lang dojo/_base/Color dojo/_base/array dojo/DeferredList dojo/dom-class dojo/dom-construct dojo/dom-style dojo/on jimu/utils esri/geometry/geometryEngine esri/geometry/Polyline esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query".split(" "),function(B,r,v,p,C,m,q,D,w,E,z,F,x,G,A,u,H,I,J){return B("ClosestInfo",null,{constructor:function(b,a,c){this.tab=b;
this.container=a;this.parent=c;this.graphicsLayer=this.incident=null;this.map=c.map;this.specialFields={};this.dateFields={}},updateForIncident:function(b,a,c){p.forEach(this.tab.tabLayers,r.hitch(this,function(d){if("undefined"!==typeof d.empty){var h=new G(d.url);w(h,"load",r.hitch(this,function(){this.tab.tabLayers=[h];this.processIncident(b,a,c)}))}else this.processIncident(b,a,c)}))},processIncident:function(b,a,c){this.container.innerHTML="";m.add(this.container,"loading");var d=[];this.incident=
b;a=z.buffer(b.geometry,a,this.parent.config.distanceSettings[this.parent.config.distanceUnits]);this.graphicsLayer=c;this.graphicsLayer.clear();var h=this.tab.tabLayers;c=[];for(var e=0;e<h.length;e++){var f=h[e],l=new J;l.returnGeometry=!0;l.geometry=a;l.outFields=this._getFields(f);"undefined"!==typeof f.queryFeatures&&c.push(f.queryFeatures(l))}(new C(c)).then(r.hitch(this,function(a){for(var c=0;c<a.length;c++){var g=a[c][1],e=this._getFields(h[c]);if((g=g.features)&&0<g.length){for(var k=0;k<
g.length;k++){for(var f=g[k],l={DISTANCE:this._getDistance(b.geometry,f.geometry)},m=0;m<e.length;m++)l[e[m]]=f.attributes[e[m]];f.attributes=l}g.sort(this._compareDistance);d.push(g[0])}}this._processResults(d)}))},_processResults:function(b){this.container.innerHTML="";m.remove(this.container,"loading");if(0===b.length)this.container.innerHTML=this.parent.nls.noFeaturesFound;else{var a=q.create("div",{style:"width:"+220*b.length+"px;"},this.container);m.add(a,"SAT_tabPanelContent");for(var c=this.parent.nls[this.parent.config.distanceUnits],
d=0;d<b.length;d++){var h=d+1,e=b[d],f=e.geometry,l=f;"point"!==f.type&&(l=f.getExtent().getCenter());var f=e.attributes,y;"point"===this.incident.geometry.type&&(y=c+": "+Math.round(100*f.DISTANCE)/100);var n="",g=0,s;for(s in f)if("DISTANCE"!==s&&3>g){var k=E.sanitizeHTML(this._getFieldValue(s,f[s])),t;if(e._layer&&e._layer.fields){var p=this._getField(e._layer.fields,s);p&&(t=p.alias)}if("undefined"===typeof t||t in[""," ",null,void 0])t=s;this.isURL(k)?k='\x3ca href\x3d"'+k+'" target\x3d"_blank" style\x3d"color: inherit;"\x3e'+
t+"\x3c/a\x3e":this.isEmail(k)&&(k='\x3ca href\x3d"mailto:'+k+'" style\x3d"color: inherit;"\x3e'+t+"\x3c/a\x3e");n+=k+"\x3cbr/\x3e";g+=1}e=q.create("div",{},a);m.add(e,"SATcolRec");g=q.create("div",{},e);m.add(g,"SATcolRecBar");k=q.create("div",{innerHTML:h},g);m.add(k,"SATcolRecNum");D.set(k,"backgroundColor",this.parent.config.color);w(k,"click",r.hitch(this,this._zoomToLocation,l));y&&(k=q.create("div",{innerHTML:y},g),m.add(k,"SATcolDistance"));this.parent.config.enableRouting&&(g=q.create("div",
{title:this.parent.nls.get_directions},g),m.add(g,"SATcolDir"),w(g,"click",r.hitch(this,this._routeToIncident,l)));n=q.create("div",{"class":"SATcolWrap",innerHTML:n},e);m.add(n,"SATcolInfo");n=new u(u.STYLE_SOLID,new v.fromString(this.parent.config.color),1);n=new A(A.STYLE_CIRCLE,24,n,new v.fromString(this.parent.config.color));e=new H;e.family="Arial";e.size="12px";h=new I(h,e,"#ffffff");h.setOffset(0,-4);null===f.OUTSIDE_POLYGON&&(e=new u(u.STYLE_SOLID,new v([0,0,0,1]),1),g=new F(l.spatialReference),
k=this.incident.geometry,"point"!==this.incident.geometry.type&&(k=this.incident.geometry.getExtent().getCenter()),g.addPath([l,k]),this.graphicsLayer.add(new x(g,e,{})));this.graphicsLayer.add(new x(l,n,f));this.graphicsLayer.add(new x(l,h,f))}}},_getField:function(b,a){for(var c=0;c<b.length;c++){var d=b[c];if(d.name===a||d.alias===a)return d}},_getFields:function(b){var a=[];if(this.tab.advStat&&this.tab.advStat.stats&&this.tab.advStat.stats.outFields&&0<this.tab.advStat.stats.outFields.length)p.forEach(this.tab.advStat.stats.outFields,
function(b){a.push(b.expression)});else{var c;if(b.infoTemplate)c=b.infoTemplate.info.fieldInfos;else if(0<this.parent.map.itemInfo.itemData.operationalLayers.length){var d=this.parent.map.itemInfo.itemData.operationalLayers;c=null;var h=0;a:for(;h<d.length;h++){var e=d[h];if("ArcGISMapServiceLayer"===e.layerType&&"undefined"!==typeof e.layers)for(var f=0;f<e.layers.length;f++){var l=e.layers[f];if(l.id===b.layerId&&l.popupInfo){c=l.popupInfo.fieldInfos;break a}}}c||(c=b.fields)}else c=b.fields;if(c)for(d=
0;d<c.length;d++)h=c[d],"undefined"!==typeof h.visible?h.visible&&a.push(h.fieldName):a.push(h.name)}var m={};b.fields&&p.forEach(b.fields,r.hitch(this,function(a){if("esriFieldTypeDate"===a.type||a.domain){if("esriFieldTypeDate"===a.type&&b.infoTemplate)for(var c in b.infoTemplate._fieldsMap)"undefined"!==typeof b.infoTemplate._fieldsMap[c].fieldName&&(b.infoTemplate._fieldsMap[c].fieldName===a.name&&"undefined"!==typeof b.infoTemplate._fieldsMap[c].format.dateFormat)&&(this.dateFields[a.name]=b.infoTemplate._fieldsMap[c].format.dateFormat);
m[a.name]=a}}));this.specialFields=m;return a},_getFieldValue:function(b,a){var c=a;if(this.specialFields[b]){var d=this.specialFields[b];"esriFieldTypeDate"===d.type?"undefined"!==this.dateFields[b]?(d=this._getDateFormat(this.dateFields[b]),c=void 0!==typeof d?(new Date(a)).toLocaleDateString(navigator.language,d):(new Date(a)).toLocaleString()):c=(new Date(a)).toLocaleString():p.some(d.domain.codedValues,function(b){if(b.code===a)return c=b.name,!0})}return c},isURL:function(b){return/(https?:\/\/|ftp:)/g.test(b)},
isEmail:function(b){return/\S+@\S+\.\S+/.test(b)},_getDateFormat:function(b){var a;switch(b){case "shortDate":a={month:"2-digit",day:"2-digit",year:"numeric"};break;case "shortDateLE":a={day:"2-digit",month:"2-digit",year:"numeric"};break;case "longMonthDayYear":a={month:"long",day:"2-digit",year:"numeric"};break;case "dayShortMonthYear":a={day:"2-digit",month:"short",year:"numeric"};break;case "longDate":a={weekday:"long",month:"long",day:"2-digit",year:"numeric"};break;case "shortDateLongTime":a=
{month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:!0};break;case "shortDateLELongTime":a={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",second:"2-digit",hour12:!0};break;case "shortDateShortTime":a={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!0};break;case "shortDateLEShortTime":a={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!0};break;
case "shortDateShortTime24":a={month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!1};break;case "shortDateLEShortTime24":a={day:"2-digit",month:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!1};break;case "longMonthYear":a={month:"long",year:"numeric"};break;case "shortMonthYear":a={month:"short",year:"numeric"};break;case "year":a={year:"numeric"}}return a},_getDistance:function(b,a){var c=0,d=this.parent.config.distanceUnits,c=z.distance(b,a,9001);
switch(d){case "miles":c*=6.21371E-4;break;case "kilometers":c*=0.0010;break;case "feet":c*=3.28084;break;case "yards":c*=1.09361;break;case "nauticalMiles":c*=5.39957E-4}return c},_compareDistance:function(b,a){return b.attributes.DISTANCE<a.attributes.DISTANCE?-1:b.attributes.DISTANCE>a.attributes.DISTANCE?1:0},_zoomToLocation:function(b){this.parent.zoomToLocation(b)},_routeToIncident:function(b){this.parent.routeToIncident(b)}})});