// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/_base/lang dojo/_base/Color dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-style dojo/number dojo/on dojo/has dijit/form/Button jimu/dijit/Popup jimu/CSVUtils jimu/utils esri/config esri/geometry/geometryEngine esri/geometry/mathUtils esri/geometry/Point esri/geometry/webMercatorUtils esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query".split(" "),
function(r,s,h,k,w,x,l,f,y,t,p,z,A,B,u,v,C,D,E,F,G,H,n,I,J,K,L,q){return r("GroupedCountInfo",[s],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],summaryGeom:null,tabNum:null,popupFields:[],groupedResults:{},symbolField:null,graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,constructor:function(a,b,c){this.tab=a;this.container=b;this.parent=c;this.config=c.config;this.graphicsLayer=null},updateForIncident:function(a,b,c,e){this.tabNum=e;this.container.innerHTML="";l.add(this.container,
"loading");this.summaryIds=[];this.summaryFeatures=[];this.groupedResults={};this.summaryGeom=b.geometry;if(0<this.tab.tabLayers.length){var d;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],d=new n(this.summaryLayer.url),d.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers[1]=d,this._initGraphicsLayer(c),this.summaryFields=this._getFields(),k.hitch(this,this._queryFeatures(b.geometry))):(d=new n(this.tab.tabLayers[0].url),p(d,"load",
k.hitch(this,function(){this.summaryLayer=d;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],e=this.parent.map.itemInfo.itemData.operationalLayers,f=0;f<e.length;f++){var g=e[f];if("undefined"!==typeof g.layerObject&&g.layerObject.infoTemplates&&(g=g.layerObject.infoTemplates[a])){d.infoTemplate=g.infoTemplate;break}}this.tab.tabLayers[1]=d;this._initGraphicsLayer(c);this.summaryFields=this._getFields();k.hitch(this,this._queryFeatures(b.geometry))})))}},
_initGraphicsLayer:function(a){null!==a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a){var b=new q;b.geometry=a;this.summaryLayer.queryIds(b,k.hitch(this,function(a){a?(this.summaryIds=
a,0<this.summaryIds.length?this._queryFeaturesByIds():this._processResults()):this._processResults()}))},_queryFeaturesByIds:function(){var a=this.summaryLayer.maxRecordCount||1E3,b=this.summaryIds.slice(0,a);this.summaryIds.splice(0,a);var a=new q,c=!1;h.some(this.summaryFields,k.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return c=!0}));a.returnGeometry=c;var e=[];h.forEach(this.summaryFields,function(a){e.push(a.field)});this.symbolField&&e.push(this.symbolField);
if(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)a.outFields=["*"];else{if(0<this.popupFields.length)for(var d=0;d<this.popupFields.length;d++){var f=this.popupFields[d];-1===e.indexOf(f)&&e.push(f)}a.outFields=e}a.objectIds=b;this.summaryLayer.queryFeatures(a,k.hitch(this,function(a){a.features&&(this.summaryFeatures=this.summaryFeatures.concat(a.features));this._processResults();0<this.summaryIds.length?(this.SA_SAT_download&&l.replace(this.SA_SAT_download,"processing","download"),
this._queryFeaturesByIds()):this.SA_SAT_download&&l.replace(this.SA_SAT_download,"download","processing")}))},_prepGroupedResults:function(){for(var a=0;a<this.summaryFeatures.length;a++){var b=this.summaryFeatures[a];if("undefined"!==typeof this.summaryFields&&0<this.summaryFields.length){var c=b.attributes[this.summaryFields[0].field];c in this.groupedResults?this.groupedResults[c].features.push(b):this.groupedResults[c]={features:[b]}}}},_prepResults:function(){for(var a in this.groupedResults){var b=
this.summaryFields[0];b.total=this.groupedResults[a].features.length;this.groupedResults[a].total=b.total;this.groupedResults[a].type=b.type;this.groupedResults[a].label=b.alias}},_processResults:function(){this._prepGroupedResults();this._prepResults();this.container.innerHTML="";l.remove(this.container,"loading");var a=this.groupedResults;if(0===Object.keys(this.groupedResults).length)this.container.innerHTML=this.parent.nls.noFeaturesFound;else{var b=Object.keys(this.groupedResults).length+1,c=
0,b=f.create("div",{style:"width:"+220*b+"px;"},this.container);l.add(b,"SAT_tabPanelContent");c=f.create("div",{},b);l.add(c,"SATcol");c=f.create("div",{"data-dojo-attach-point":"SA_SAT_download",innerHTML:this.parent.nls.downloadCSV},c);l.add(c,["btnExport","download"]);p(c,"click",k.hitch(this,this._exportToCSV));var e=Object.keys(a).sort(),d;for(d in e){var c=e[d],m=a[c],h=v.sanitizeHTML(c),c=c===this.parent.nls.area||c===this.parent.nls.length?m.total:Math.round(m.total);isNaN(c)&&(c=0);var n=
f.create("div",{"class":"SATcol"},b),g=f.create("div",{style:"max-height: 45px;"},n);f.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:"pre"===m.type?m.label.trim():h},g);f.create("div",{"class":"SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:"pre"===m.type?h:m.label.trim()},g);f.create("div",{"class":""!==m.label?"colGroupedSummary":"colSummary",innerHTML:t.format(c)},n)}if(null!==this.graphicsLayer){this.graphicsLayer.clear();this.tab.tabLayers[1].clear();
if(this.summaryFeatures)for(a=0;a<this.summaryFeatures.length;a++)d=this.summaryFeatures[a],this.lyrSymbol?d.symbol=this.lyrSymbol:this.graphicsLayer.renderer&&(b=this.graphicsLayer.renderer.getSymbol(d),d.symbol=b),this.graphicsLayer.add(d),this.tab.tabLayers[1].add(d);this.graphicsLayer.setVisibility(!0);this.parent._toggleTabLayersNew(this.tabNum);this.tab.retsore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,tab:this.tabNum})}}},_exportToCSV:function(){if(0===this.summaryFeatures.length)return!1;
var a;a=this.tab.label?this.tab.label:this.tab.layers;var b=[],c=[];h.forEach(this.summaryFeatures,function(a){b.push(a.attributes)});if(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)for(var e in b[0])c.push(e);else for(e=0;e<this.summaryFields.length;e++)c.push(this.summaryFields[e].field);u.exportCSV(a,b,c)},_getFields:function(){var a=[];if("undefined"!==typeof this.tab.advStat){var b=this.tab.advStat.stats,c;for(c in b)0<b[c].length&&h.forEach(b[c],function(b){a.push({field:b.expression,
alias:b.label+"",type:c,total:0})})}return a}})});