// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/Evented dojo/_base/array dojo/_base/lang dojo/_base/Color dojo/dom dojo/dom-class dojo/dom-construct dojo/dom-style dojo/number dojo/on dojo/has dijit/form/Button jimu/dijit/Popup jimu/CSVUtils jimu/utils esri/config esri/geometry/geometryEngine esri/geometry/mathUtils esri/geometry/Point esri/geometry/webMercatorUtils esri/graphic esri/layers/FeatureLayer esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/Font esri/symbols/TextSymbol esri/tasks/query".split(" "),
function(t,u,l,e,z,A,m,n,B,v,q,C,D,E,w,x,F,p,G,H,I,J,r,K,L,M,N,s){return t("SummaryInfo",[u],{summaryLayer:null,summaryFields:[],summaryIds:[],summaryFeatures:[],summaryGeom:null,tabNum:null,symbolField:null,graphicsLayer:null,lyrRenderer:null,lyrSymbol:null,constructor:function(a,b,d){this.tab=a;this.container=b;this.parent=d;this.config=d.config;this.graphicsLayer=null},updateForIncident:function(a,b,d,c){this.tabNum=c;this.container.innerHTML="";m.add(this.container,"loading");this.summaryIds=
[];this.summaryFeatures=[];this.summaryGeom=b.geometry;if(0<this.tab.tabLayers.length){var f;"undefined"!==typeof this.tab.tabLayers[0].infoTemplate?(this.summaryLayer=this.tab.tabLayers[0],f=new r(this.summaryLayer.url),f.infoTemplate=this.tab.tabLayers[0].infoTemplate,this.tab.tabLayers.push(f),this._initGraphicsLayer(d),this.summaryFields=this._getFields(this.summaryLayer),e.hitch(this,this._queryFeatures(b.geometry))):(f=new r(this.tab.tabLayers[0].url),q(f,"load",e.hitch(this,function(){this.summaryLayer=
f;if(-1<this.tab.tabLayers[0].url.indexOf("MapServer"))for(var a=this.tab.tabLayers[0].url.split("MapServer/")[1],c=this.parent.map.itemInfo.itemData.operationalLayers,k=0;k<c.length;k++){var h=c[k];if("undefined"!==typeof h.layerObject&&h.layerObject.infoTemplates&&(h=h.layerObject.infoTemplates[a])){f.infoTemplate=h.infoTemplate;break}}this.tab.tabLayers.push(f);this._initGraphicsLayer(d);this.summaryFields=this._getFields(this.summaryLayer);e.hitch(this,this._queryFeatures(b.geometry))})))}},_initGraphicsLayer:function(a){null!==
a&&(this.graphicsLayer=a,this.graphicsLayer.clear(),this.summaryLayer&&this.summaryLayer.renderer&&(this.lyrRenderer=this.summaryLayer.renderer,this.graphicsLayer.renderer=this.lyrRenderer,"undefined"!==typeof this.summaryLayer.renderer.attributeField?this.symbolField=this.summaryLayer.renderer.attributeField:this.lyrSymbol=this.lyrRenderer.symbol))},_queryFeatures:function(a){var b=new s;b.geometry=a;this.summaryLayer.queryIds(b,e.hitch(this,function(a){a?(this.summaryIds=a,0<this.summaryIds.length?
this._queryFeaturesByIds():this._processResults()):this._processResults()}))},_queryFeaturesByIds:function(){var a=this.summaryLayer.maxRecordCount||1E3,b=this.summaryIds.slice(0,a);this.summaryIds.splice(0,a);var a=new s,d=!1;l.some(this.summaryFields,e.hitch(this,function(a){if("area"===a.type||"length"===a.type||this.graphicsLayer)return d=!0}));a.returnGeometry=d;var c=[];l.forEach(this.summaryFields,function(a){c.push(a.field)});this.symbolField&&c.push(this.symbolField);a.outFields=!0===this.config.csvAllFields||
"true"===this.config.csvAllFields?["*"]:c;a.objectIds=b;this.summaryLayer.queryFeatures(a,e.hitch(this,function(a){a.features&&(this.summaryFeatures=this.summaryFeatures.concat(a.features));this._processResults();0<this.summaryIds.length?(this.SA_SAT_download&&m.replace(this.SA_SAT_download,"processing","download"),this._queryFeaturesByIds()):this.SA_SAT_download&&m.replace(this.SA_SAT_download,"download","processing")}))},_prepResults:function(){for(var a=0;a<this.summaryFields.length;a++){var b=
this.summaryFields[a],d=b.field,c=b.total;switch(b.type){case "count":c=this.summaryFeatures.length;break;case "area":c=this._getArea();break;case "length":c=this._getLength();break;case "sum":c=this._getSum(d);break;case "avg":c=this._getSum(d)/this.summaryFeatures.length;break;case "min":c=this._getMin(d);break;case "max":c=this._getMax(d)}b.total=c}},_sortResults:function(a){return function(b,d){return b.attributes[a]<d.attributes[a]?-1:b.attributes[a]>d.attributes[a]?1:0}},_getSum:function(a){var b=
0;l.forEach(this.summaryFeatures,function(d){b+=d.attributes[a]});return b},_getMin:function(a){this.summaryFeatures.sort(this._sortResults(a));return this.summaryFeatures[0].attributes[a]},_getMax:function(a){this.summaryFeatures.sort(this._sortResults(a));this.summaryFeatures.reverse();return this.summaryFeatures[0].attributes[a]},_getArea:function(){var a=0,b=e.clone(this.config.distanceSettings);b.miles=109413;b.kilometers=109414;b.feet=109405;b.meters=109404;b.yards=109442;b.nauticalMiles=109409;
var d=b[this.config.distanceUnits];l.forEach(this.summaryFeatures,e.hitch(this,function(b){b=p.intersect(b.geometry,this.summaryGeom);null!==b&&(a+=p.geodesicArea(b,d))}));return a},_getLength:function(){var a=0,b=this.config.distanceSettings[this.config.distanceUnits];l.forEach(this.summaryFeatures,e.hitch(this,function(d){d=p.intersect(d.geometry,this.summaryGeom);null!==d&&(a+=p.geodesicLength(d,b))}));return a},_processResults:function(){this._prepResults();this.container.innerHTML="";m.remove(this.container,
"loading");if(0===this.summaryFeatures.length)this.container.innerHTML=this.parent.nls.noFeaturesFound;else{var a=this.summaryFields,b=0,d=n.create("div",{style:"width:"+220*(a.length+1)+"px;"},this.container);m.add(d,"SAT_tabPanelContent");var c=n.create("div",{},d);m.add(c,"SATcol");c=n.create("div",{"data-dojo-attach-point":"SA_SAT_download",innerHTML:this.parent.nls.downloadCSV},c);m.add(c,["btnExport","download"]);q(c,"click",e.hitch(this,this._exportToCSV));for(c=0;c<a.length;c++){var b=a[c],
f=x.sanitizeHTML(b.alias?b.alias:"")+"\x3cbr/\x3e",b=b.alias===this.parent.nls.area||b.alias===this.parent.nls.length?b.total:Math.round(b.total);isNaN(b)&&(b=0);var g=n.create("div",{"class":"SATcol"},d),y=n.create("div",{style:"max-height: 60px;"},g);n.create("div",{"class":" SATcolWrap",style:"max-height: 30px; overflow: hidden;",innerHTML:f},y);n.create("div",{"class":" colSummary",innerHTML:v.format(b)},g)}if(null!==this.graphicsLayer){this.graphicsLayer.clear();this.tab.tabLayers[1].clear();
if(this.summaryFeatures)for(a=0;a<this.summaryFeatures.length;a++)d=this.summaryFeatures[a],this.lyrSymbol?d.symbol=this.lyrSymbol:this.graphicsLayer.renderer&&(c=this.graphicsLayer.renderer.getSymbol(d),d.symbol=c),this.graphicsLayer.add(d),this.tab.tabLayers[1].add(d);this.graphicsLayer.setVisibility(!0);this.parent._toggleTabLayersNew(this.tabNum);this.tab.restore&&this.emit("summary-complete",{bubbles:!0,cancelable:!0,tab:this.tabNum})}}},_exportToCSV:function(){if(0===this.summaryFeatures.length)return!1;
var a;a=this.tab.label?this.tab.label:this.tab.layers;var b=[],d=[];l.forEach(this.summaryFeatures,function(a){b.push(a.attributes)});if(!0===this.config.csvAllFields||"true"===this.config.csvAllFields)for(var c in b[0])d.push(c);else for(c=0;c<this.summaryFields.length;c++)d.push(this.summaryFields[c].field);w.exportCSV(a,b,d)},_getFields:function(a){var b=[];if(this.tab.advStat){a=this.tab.advStat.stats;for(var d in a)0<a[d].length&&l.forEach(a[d],function(a){b.push({field:a.expression,alias:a.label+
"",type:d,total:0})});return b}var c;if(a.infoTemplate)c=a.infoTemplate.info.fieldInfos;else if(-1<this.tab.tabLayers[0].url.indexOf("MapServer")){var f=this.tab.tabLayers[0].url.split("MapServer/")[1],g=this.parent.map.itemInfo.itemData.operationalLayers;c=null;for(var e=0;e<g.length;e++){var k=g[e];if(k.layerObject.infoTemplates&&(k=k.layerObject.infoTemplates[f])){c=k.infoTemplate.info.fieldInfos;break}}}else c=a.fields;c||(c=a.fields);for(f=0;f<c.length;f++)if(g=c[f],"undefined"!==typeof a.fields){var e=
a.fields[f].type,h;if(g.name!==a.objectIdField&&("esriFieldTypeDouble"===e||"esriFieldTypeInteger"===e||"esriFieldTypeSmallInteger"===e))"undefined"!==typeof g.visible?g.visible&&(h={field:g.fieldName,alias:g.label,type:"sum",total:0}):h={field:g.name,alias:g.alias,type:"sum",total:0},h&&b.push(h),h=null}return b}})});