// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"url:widgets/NearMe/item-list.html":'\x3cdiv class\x3d"esriCTItemlList"\x3e\r\n    \x3cdiv class\x3d"esriCTBackButton"\x3e\r\n        \x3cdiv class\x3d"esriCTItemLeftArrow"\x3e\r\n        \x3c/div\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"esriCTItemRightArrow"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"esriCTItemCount esriCTLoadingIcon"\x3e\r\n    \x3c/div\x3e\r\n    \x3cdiv class\x3d"esriCTItemName"\x3e\r\n    \x3c/div\x3e\r\n\x3c/div\x3e\r\n'}});
define("dojo/_base/declare dijit/_WidgetBase dojo/dom-construct dojo/query dojo/_base/array dojo/_base/lang dijit/layout/ContentPane dojo/dom-attr dojo/dom-style dojo/dom-class dojo/on dojo/Deferred dojo/Evented dojo/promise/all jimu/dijit/Message jimu/dijit/TabContainer dojo/text!./item-list.html esri/Color esri/dijit/Directions esri/dijit/PopupTemplate esri/graphic esri/geometry/Point esri/geometry/Polyline esri/geometry/Polygon esri/SpatialReference esri/geometry/geometryEngine esri/layers/FeatureLayer esri/layers/GraphicsLayer esri/symbols/SimpleFillSymbol esri/symbols/SimpleLineSymbol esri/symbols/SimpleMarkerSymbol esri/tasks/query esri/units dojo/_base/fx dojo/number dijit/registry".split(" "),function(C,
D,l,m,E,k,w,p,e,h,q,s,F,x,G,H,I,r,J,K,t,L,y,M,u,N,O,P,z,n,A,Q,R,S,B,g){return C([D,F],{_itemListTemplate:I,_serviceArea:null,_operationalLayers:null,_selectedPoint:null,_panels:{},_currentPanel:null,map:null,config:null,folderUrl:null,loading:null,nls:null,parentDiv:null,outerContainer:null,_featureListContent:null,_featureInfoPanel:null,_directionInfoPanel:null,_tabContainer:null,_isNoFeature:null,_isSlide:!0,_loadAttachmentTimer:null,_failedLayers:[],_routeCalculated:!1,_selectedLayer:null,_selectedItem:null,
_selectedFeature:null,_selectedFeatureItem:null,_featureGraphicsLayer:null,_directionsWidget:null,postCreate:function(){this.domNode=l.create("div",{"class":"esriCTItemListMainContainer"},this.outerContainer);this._createPanels();this._loadFeatureLayers();this._featureGraphicsLayer=new P;this.map.addLayer(this._featureGraphicsLayer)},_createPanels:function(){var a;this._panels.layerListPanel=l.create("div",{"class":"esriCTLayerList"},this.domNode);this._panels.featureListPanel=l.create("div",{"class":"esriCTFeatureList"},
this.domNode);a=l.toDom(this._itemListTemplate).childNodes[0];h.add(a,"esriCTPanelHeader");this._panels.featureListPanel.appendChild(a);this._featureListContent=l.create("div",{"class":"esriCTFeatureListContent"},null);e.set(this._featureListContent,"color",this.config.fontColor);this._panels.featureListPanel.appendChild(this._featureListContent);this._attachEventOnBackButton(this._panels.featureListPanel);this._panels.infoPanel=l.create("div",{"class":"esriCTDirectionInfoPanel"},this.domNode);a=
l.toDom(this._itemListTemplate).childNodes[0];h.add(a,"esriCTPanelHeader");this._panels.infoPanel.appendChild(a);this._attachEventOnBackButton(this._panels.infoPanel);this._featureInfoPanel=new w({id:"divFeatureInfoContent"},null);this._featureInfoPanel.startup();this.map.webMapResponse.itemInfo.itemData.applicationProperties&&this.map.webMapResponse.itemInfo.itemData.applicationProperties.viewing.routing.enabled?(this._directionInfoPanel=new w({id:"divDirectionInfoContent"},null),this._directionInfoPanel.startup(),
this._tabContainer=new H({tabs:[{title:this.nls.informationTabTitle,content:this._featureInfoPanel},{title:this.nls.directionTabTitle,content:this._directionInfoPanel}]},l.create("div",{"class":"esriCTTabContainer"},this._panels.infoPanel)),this._tabContainer.startup(),this._tabContainer.on("tabChanged",k.hitch(this,function(a){this.emit("tab-change",a);a===this.nls.directionTabTitle&&!this._routeCalculated&&this._initializeDirectionWidget();this.parentDivId&&(g.byId(this.parentDivId)&&g.byId(this.parentDivId).resize)&&
g.byId(this.parentDivId).resize()}))):(this._panels.infoPanel.appendChild(this._featureInfoPanel.domNode),h.add(this._featureInfoPanel.domNode,"esriCTFeatureInfo"),(a=m(".esriCTItemListMainContainer .esriCTDirectionInfoPanel .esriCTPanelHeader"))&&h.add(a[0],"esriCTBorderBottom"));this.parentDivId&&(g.byId(this.parentDivId)&&g.byId(this.parentDivId).resize)&&g.byId(this.parentDivId).resize()},_attachEventOnBackButton:function(a){var b,c;b=m(".esriCTItemlList",a)[0];c=m(".esriCTBackButton",a)[0];b&&
c&&this.own(q(b,"click",k.hitch(this,function(a){a.stopPropagation();"none"!==e.get(c,"display")&&this._isSlide&&(this._isSlide=!1,this._selectedItem=null,this._clearGrahics(),this._isFeatureList?(this._isFeatureList=!1,this._clearDirections(),this._showPanel("featureListPanel",!0)):(this.loading.hide(),this._clearContent(this._featureListContent),this.config.selectedSearchLayerOnly&&this.showAllLayers(),this._resetFilter(this._selectedLayer.layerIndex),this._selectedLayer=null,this._isFeatureList=
!1,this._showPanel("layerListPanel",!0)))})))},_loadFeatureLayers:function(){var a,b;this._operationalLayers=[];for(b=0;b<this.config.searchLayers.length;b++)this.config.searchLayers[b].popupInfo&&(a=new O(this.config.searchLayers[b].url,{infoTemplate:new K(this.config.searchLayers[b].popupInfo)}),this.config.searchLayers[b].id&&(a.id=this.config.searchLayers[b].id),a.title=this.config.searchLayers[b].title,this.config.searchLayers[b].definitionExpression&&a.setDefinitionExpression(this.config.searchLayers[b].definitionExpression),
this.config.searchLayers[b].renderer&&a.setRenderer(this.config.searchLayers[b].renderer),a.index=b,a.layerIndex=this._operationalLayers.length,a.isMapServer=this.config.searchLayers[b].isMapServer,a.showAttachments=this.config.searchLayers[b].popupInfo.showAttachments,this._operationalLayers.push(a))},hasValidLayers:function(){return this._operationalLayers&&0<this._operationalLayers.length?!0:!1},_clearContent:function(a){a&&l.empty(a)},displayLayerList:function(a,b){var c,d=[];this.loading.hide();
this._isSlide=this._isNoFeature=!0;this.clearResultPanel();this.config.selectedSearchLayerOnly&&this.showAllLayers();this._setSeachedLocation(a);this._setServiceArea(b);this._failedLayers=[];if(1<this._operationalLayers.length){this._currentPanel=this._panels.layerListPanel;e.set(this._currentPanel,"display","block");e.set(this._currentPanel,"left","0px");for(c=0;c<this._operationalLayers.length;c++)this._resetFilter(this._operationalLayers[c].layerIndex),this._createItemTemplate(this._operationalLayers[c],
d)}else this._resetFilter(this._operationalLayers[0].layerIndex),this._onSingleLayerFound(d);x(d).then(k.hitch(this,function(){this._onFeatureCountComplete()}))},_onSingleLayerFound:function(a){var b;b=new s;a.push(b);(a=m(".esriCTBackButton",this._panels.featureListPanel)[0])&&e.set(a,"display","none");this._currentPanel=this._panels.featureListPanel;e.set(this._currentPanel,"display","block");e.set(this._currentPanel,"left","0px");this._displayFeatureList(this._operationalLayers[0],b)},_createItemTemplate:function(a,
b){var c;c=l.toDom(this._itemListTemplate).childNodes[0];h.add(c,"esriCTDisabled");e.set(c,"color",this.config.fontColor);this._currentPanel.appendChild(c);this._setItemName(c,a.title);this._queryForCountOnly(c,a,b);this._attachClickEvent(c,a,!0)},_setItemName:function(a,b){var c=m(".esriCTItemName",a)[0];c&&(p.set(c,"innerHTML",b),p.set(c,"title",b))},_attachClickEvent:function(a,b){this.own(q(a,"click",k.hitch(this,function(c){!h.contains(a,"esriCTDisabled")&&this._isSlide&&(c.stopPropagation(),
this._isSlide=!1,this._selectedItem=a,this._showPanel("featureListPanel"),this._displayFeatureList(b,null))})))},_displayFeatureList:function(a,b){this._clearContent(this._featureListContent);this._selectedLayer=a;if(this.map.webMapResponse.itemInfo.itemData.applicationProperties&&this.map.webMapResponse.itemInfo.itemData.applicationProperties.viewing.routing.enabled){var c=m(".jimu-tab",this._panels.infoPanel),d=m(".jimu-tab .control",this._panels.infoPanel),f=m(".esriCTItemListMainContainer .esriCTDirectionInfoPanel .esriCTPanelHeader");
d&&d[0]&&"esriGeometryPolygon"===a.geometryType&&this.config.intersectSearchedLocation?(h.add(c[0],"esriCTOverrideHeight"),h.add(d[0],"esriCTHidden"),h.add(f[0],"esriCTBorderBottom")):d&&d[0]&&(h.remove(c[0],"esriCTOverrideHeight"),h.remove(d[0],"esriCTHidden"),h.remove(f[0],"esriCTBorderBottom"))}this._setItemName(this._panels.featureListPanel,this._selectedLayer.title);this._queryForFeatureList(b)},_getQueryParams:function(){var a=new Q;a.geometry=this._serviceArea||this.map.extent;a.spatialRelationship=
"esriSpatialRelIntersects";a.outFields=["*"];return a},_queryForCountOnly:function(a,b,c){var d,f;f=this._getQueryParams();this.config.intersectSearchedLocation&&"esriGeometryPolygon"===b.geometryType&&(f.geometry=this._selectedPoint.geometry);d=new s;b.queryCount(f,k.hitch(this,function(b){this._setItemCount(a,b,!0,!1);d.resolve()}),k.hitch(this,function(){this._setItemCount(a,0,!0,!0);this._failedLayers.push(b.title);d.resolve()}));c.push(d)},_onFeatureCountComplete:function(){this._isNoFeature&&
(this.clearResultPanel(),e.set(this._panels.layerListPanel,"display","block"),e.set(this._panels.layerListPanel,"left","0px"),l.create("div",{"class":"esriCTNoFeatureFound",innerHTML:this.nls.noFeatureFoundText},this._panels.layerListPanel));if(this._failedLayers.length){var a=this.nls.unableToFetchResults+"\n\x3c/t\x3e\x3cul\x3e\x3cli\x3e"+this._failedLayers.join("\n \x3c/li\x3e\x3cli\x3e")+"\x3c/li\x3e\x3c/ul\x3e";this._showMessage(a)}this.loading.hide();this.parentDivId&&(g.byId(this.parentDivId)&&
g.byId(this.parentDivId).resize)&&g.byId(this.parentDivId).resize()},_queryForFeatureList:function(a){this.loading.show();var b=this._getQueryParams();this.config.intersectSearchedLocation&&"esriGeometryPolygon"===this._selectedLayer.geometryType&&(b.geometry=this._selectedPoint.geometry);this._hideAllLayers();this._selectedLayer.queryFeatures(b,k.hitch(this,function(b){0<b.features.length&&(this._isNoFeature=!1,this._creatFeatureList(b.features));a&&a.resolve()}),k.hitch(this,function(){this.loading.hide();
this._failedLayers.push(this._selectedLayer.title);a&&a.resolve()}))},_setItemCount:function(a,b,c,d){var f=m(".esriCTItemCount",a)[0];f&&(h.remove(f,"esriCTLoadingIcon"),d?p.set(f,"innerHTML","(-)"):c?(p.set(f,"innerHTML","("+B.format(b)+")"),b&&(this._isNoFeature=!1,h.remove(a,"esriCTDisabled"))):p.set(f,"innerHTML",B.format(b.toFixed(2))+" "+this.config.bufferDistanceUnit.acronym))},_creatFeatureList:function(a){var b,c,d="",f;a=this._getSortedFeatureList(a);for(b=0;b<a.length;b++)d&&(d+=","),
d+=a[b].attributes[this._selectedLayer.objectIdField],c=l.toDom(this._itemListTemplate).childNodes[0],h.add(c,"esriCTFeatureListItem"),this._featureListContent.appendChild(c),this._setItemName(c,a[b].getTitle()),"polygon"===a[b].geometry.type&&this.config.intersectSearchedLocation?(f=m(".esriCTItemCount",c)[0])&&h.remove(f,"esriCTLoadingIcon"):this._setItemCount(c,a[b].distanceToLocation,!1,!1),this._attachEventOnFeatureDiv(c,a[b]);this.parentDivId&&(g.byId(this.parentDivId)&&g.byId(this.parentDivId).resize)&&
g.byId(this.parentDivId).resize();this._displayFilteredFeatures(d);this.loading.hide()},_displayFilteredFeatures:function(a){this.config.selectedSearchLayerOnly&&(this._showHideOperationalLayer(this._selectedLayer.url,this._selectedLayer.id,!0),a=this._selectedLayer.objectIdField+" in ("+a+")",this._selectedLayer.setDefinitionExpression(a),this._setFilterOnMapLayer(a,this._selectedLayer.id,this._selectedLayer.url,this._selectedLayer.isMapServer))},_setFilterOnMapLayer:function(a,b,c,d){var f=[];if(b)if(d){if(f=
b.substring(0,b.lastIndexOf("_")),b=this.map.getLayer(f))f=[],c=c[c.length-1],f[c]=a,b.setLayerDefinitions(f)}else(b=this.map.getLayer(b))&&b.setDefinitionExpression(a)},_resetFilter:function(a){if(this.config.selectedSearchLayerOnly){var b;b=this.config.searchLayers[this._operationalLayers[a].index];this._operationalLayers[a].setDefinitionExpression(b.definitionExpression);this._setFilterOnMapLayer(b.definitionExpression,this._operationalLayers[a].id,this._operationalLayers[a].url,this._operationalLayers[a].isMapServer)}},
_getSortedFeatureList:function(a){var b;for(b=0;b<a.length;b++)a[b].distanceToLocation=N.distance(this._selectedPoint.geometry,a[b].geometry,this.config.bufferDistanceUnit.distanceUnit);a.sort(function(a,b){return a.distanceToLocation-b.distanceToLocation});return a},_attachEventOnFeatureDiv:function(a,b){this.own(q(a,"click",k.hitch(this,function(){this._setItemName(this._panels.infoPanel,this._selectedLayer.title);this._showPanel("infoPanel");this._tabContainer&&this._tabContainer.selectTab(this.nls.informationTabTitle);
this._selectedFeatureItem=a;this._selectedFeature=b;this._isFeatureList=!0;this._clearDirections();this._highlightFeatureOnMap();this._displayFeatureInfo(b);this.parentDivId&&(g.byId(this.parentDivId)&&g.byId(this.parentDivId).resize)&&g.byId(this.parentDivId).resize()})))},_displayFeatureInfo:function(a){var b;this._loadAttachmentTimer&&clearTimeout(this._loadAttachmentTimer);this._featureInfoPanel&&(this._featureInfoPanel.set("content",a.getContent()),this._checkAttachments());this.config.zoomToFeature&&
("point"===a.geometry.type?(a=a.geometry,b=this._selectedPoint.geometry,a={paths:[[[a.x,a.y],[b.x,b.y]]],spatialReference:this.map.spatialReference},a=new y(a),this.map.setExtent(a.getExtent().expand(1.5))):this.map.setExtent(a.geometry.getExtent().expand(1.5)))},_checkAttachments:function(){if(this._selectedLayer.hasAttachments&&this._selectedLayer.showAttachments){this.loading.show();var a=m(".attachmentsSection",this._featureInfoPanel.domNode)[0];l.empty(a);h.remove(a,"hidden");this._loadAttachmentTimer=
setTimeout(k.hitch(this,function(){this._showAttachments(this._selectedFeature,a,this._selectedLayer)}),500)}},_showAttachments:function(a,b,c){var d,f,v,e,m,p=[],n;a=a.attributes[c.objectIdField];l.empty(b);c.queryAttachmentInfos(a,k.hitch(this,function(a){if(a&&0<a.length){l.create("div",{innerHTML:this.nls.attachmentHeader,"class":"esriCTAttachmentHeader"},b);d=l.create("div",{"class":"esriCTThumbnailContainer"},b);for(m=0;m<a.length;m++)n=new s,e=this.folderUrl+"images/no-attachment.png",-1<a[m].contentType.indexOf("image")&&
(e=a[m].url),v=l.create("span",{"class":"esriCTAttachmentHolder col"},d),h.add(v,"esriCTImageLoader"),f=l.create("img",{alt:a[m].url,"class":"esriCTAttachmentImg esriCTAutoHeight",src:e},v),this._attachEventOnImage(f,n),p.push(n)}x(p).then(k.hitch(this,this._onAllAttachmentLoad));this.parentDivId&&(g.byId(this.parentDivId)&&g.byId(this.parentDivId).resize)&&g.byId(this.parentDivId).resize()}))},_attachEventOnImage:function(a,b){this.own(q(a,"load",k.hitch(this,function(a){this._onImageLoad(a);b.resolve()})));
this.own(q(a,"click",k.hitch(this,this._displayImageAttachments)));this.own(q(a,"error",k.hitch(this,function(a){this._onError(a);b.resolve()})))},_displayImageAttachments:function(a){window.open(a.target.alt)},_onImageLoad:function(a){h.remove(a.target.parentNode,"esriCTImageLoader");this._setImageDimensions(a.target)},_setImageDimensions:function(a){var b,c;c=a.parentElement;if(a&&0<a.offsetHeight&&(p.set(a,"originalHeight",a.offsetHeight),e.set(a,"maxHeight",a.offsetHeight+"px"),e.set(a,"maxWidth",
a.offsetWidth+"px"),b=parseFloat(p.get(a,"originalHeight")),c.offsetHeight<a.offsetHeight||b>c.offsetHeight))b=a.offsetWidth/a.offsetHeight,c=c.offsetHeight-2,b=Math.floor(c*b),h.remove(a,"esriCTAutoHeight"),e.set(a,"width",b+"px"),e.set(a,"height",c+"px")},_onError:function(a){h.remove(a.target.parentNode,"esriCTImageLoader")},_onAllAttachmentLoad:function(){this.loading.hide()},_setSeachedLocation:function(a){this._selectedPoint=a},_setServiceArea:function(a){this._serviceArea=a},clearResultPanel:function(){this._isFeatureList=
!1;this._clearContent(this._panels.layerListPanel);e.set(this._panels.featureListPanel,"display","none");e.set(this._panels.infoPanel,"display","none");this._clearContent(this._featureListContent);this._clearDirections();this._clearGrahics()},removeGraphicsLayer:function(){this._featureGraphicsLayer&&(this.map.removeLayer(this._featureGraphicsLayer),this._featureGraphicsLayer=null)},_clearGrahics:function(){this._featureGraphicsLayer&&this._featureGraphicsLayer.clear()},_showPanel:function(a,b){e.set(this._panels[a],
{display:"block",left:"-100%"});b?(this._slide(this._panels[a],-100,0),this._slide(this._currentPanel,0,100)):(this._slide(this._currentPanel,0,-100),this._slide(this._panels[a],100,0));this._currentPanelName=a;this._currentPanel=this._panels[a];this.parentDivId&&(g.byId(this.parentDivId)&&g.byId(this.parentDivId).resize)&&g.byId(this.parentDivId).resize()},_slide:function(a,b,c){e.set(a,"display","block");e.set(a,"left",b+"%");S.animateProperty({node:a,properties:{left:{start:b,end:c,units:"%"}},
duration:300,onEnd:k.hitch(this,function(){e.set(a,"left",c);0===c?e.set(a,"display","block"):e.set(a,"display","none");this._isSlide=!0})}).play()},_showMessage:function(a){(new G({message:a})).message=a},_initializeDirectionWidget:function(){var a;this._directionsWidget||(g.byId("directionDijit")&&g.byId("directionDijit").destroy(),a={id:"directionDijit",map:this.map,directionsLengthUnits:R[this.config.directionLengthUnit.routeUnit],showTrafficOption:!1,dragging:!1,routeTaskUrl:this.config.routeService,
routeSymbol:new n(this.config.symbols.routeSymbol)},this._directionsWidget=new J(a,l.create("div",{},null)),this._directionsWidget.startup(),this._directionsWidget.on("directions-finish",k.hitch(this,function(){this._directionsWidget.zoomToFullRoute();this.parentDivId&&(g.byId(this.parentDivId)&&g.byId(this.parentDivId).resize)&&g.byId(this.parentDivId).resize();this.loading.hide()})),this._directionInfoPanel.set("content",this._directionsWidget.domNode));this._routeSelectedLocations()},_clearDirections:function(){this._routeCalculated=
!1;this._directionsWidget&&this._directionsWidget.clearDirections()},_routeSelectedLocations:function(){var a=[];this._clearDirections();this._selectedPoint&&this._selectedFeature&&(this.loading.show(),a.push(this._selectedPoint),"point"===this._selectedFeature.geometry.type?a.push(this._selectedFeature):"polygon"===this._selectedFeature.geometry.type?a.push(this._selectedFeature.geometry.getCentroid()):a.push(this._selectedFeature.geometry.getPoint(0,0)),this._directionsWidget.updateStops(a).then(k.hitch(this,
function(){this._directionsWidget.getDirections();this._routeCalculated=!0}),k.hitch(this,function(){this.loading.hide();this._showMessage(this.nls.failedToGenerateRouteMsg)})))},_highlightFeatureOnMap:function(){var a;this._clearGrahics();a=this._getHighLightSymbol(this._selectedFeature,this._selectedLayer);this._featureGraphicsLayer.add(a)},_getHighLightSymbol:function(a,b){switch(a.geometry.type){case "point":return this._getPointSymbol(a,b);case "polyline":return this._getPolyLineSymbol(a,b);
case "polygon":return this._getPolygonSymbol(a)}},_getPointSymbol:function(a,b){var c,d,f,e,g;d=!1;c=new A(A.STYLE_SQUARE,null,new n(n.STYLE_SOLID,new r([0,255,255,1]),3));c.setColor(null);c.size=30;if(b&&b.renderer)if(b.renderer.symbol)c=this._updatePointSymbolProperties(c,b.renderer.symbol);else if(b.renderer.infos&&0<b.renderer.infos.length){for(g=0;g<b.renderer.infos.length;g++)b.typeIdField?f=a.attributes[b.typeIdField]:b.renderer.attributeField&&(f=a.attributes[b.renderer.attributeField]),e=
b.renderer.infos[g].value,void 0!==f&&(null!==f&&""!==f&&void 0!==e&&null!==e&&""!==e)&&f.toString()===e.toString()&&(d=!0,c=this._updatePointSymbolProperties(c,b.renderer.infos[g].symbol));d||b.renderer.defaultSymbol&&(c=this._updatePointSymbolProperties(c,b.renderer.defaultSymbol))}d=new L(a.geometry.x,a.geometry.y,new u({wkid:a.geometry.spatialReference.wkid}));return new t(d,c,a.attributes)},_updatePointSymbolProperties:function(a,b){var c,d;b.hasOwnProperty("height")&&b.hasOwnProperty("width")&&
(c=b.height,d=b.width,c=(c>d?c:d)+10,a.size=c);if(b.hasOwnProperty("size")&&(!c||c<b.size))a.size=b.size+10;b.hasOwnProperty("xoffset")&&(a.xoffset=b.xoffset);b.hasOwnProperty("yoffset")&&(a.yoffset=b.yoffset);return a},_getPolyLineSymbol:function(a,b){var c,d,f,e;c=5;if(b&&b.renderer)if(b.renderer.symbol&&b.renderer.symbol.hasOwnProperty("width"))c=b.renderer.symbol.width;else if(b.renderer.infos&&0<b.renderer.infos.length)for(e=0;e<b.renderer.infos.length;e++)b.typeIdField?d=a.attributes[b.typeIdField]:
b.renderer.attributeField&&(d=a.attributes[b.renderer.attributeField]),f=b.renderer.infos[e].value,void 0!==d&&(null!==d&&""!==d&&void 0!==f&&null!==f&&""!==f)&&(d.toString()===f.toString()&&b.renderer.infos[e].symbol.hasOwnProperty("width"))&&(c=b.renderer.infos[e].symbol.width);else b.renderer.defaultSymbol&&b.renderer.defaultSymbol.hasOwnProperty("width")&&(c=b.renderer.defaultSymbol.width);c=new n(n.STYLE_SOLID,new r([0,255,255,1]),c);d=new y(new u({wkid:a.geometry.spatialReference.wkid}));a.geometry.paths&&
0<a.geometry.paths.length&&d.addPath(a.geometry.paths[0]);return new t(d,c,a.attributes)},_getPolygonSymbol:function(a){var b,c;b=new z(z.STYLE_SOLID,new n(n.STYLE_SOLID,new r([0,255,255,1]),4),new r([0,0,0,0]));c=new M(new u({wkid:a.geometry.spatialReference.wkid}));a.geometry.rings&&(c.rings=k.clone(a.geometry.rings));return new t(c,b,a.attributes)},_hideAllLayers:function(){if(this.config.selectedSearchLayerOnly){var a;for(a=0;a<this.config.searchLayers.length;a++)this._showHideOperationalLayer(this.config.searchLayers[a].url,
this.config.searchLayers[a].id,!1)}},showAllLayers:function(){var a;for(a=0;a<this.config.searchLayers.length;a++)this._showHideOperationalLayer(this.config.searchLayers[a].url,this.config.searchLayers[a].id,!0)},_showHideOperationalLayer:function(a,b,c){var d,f,e,g;e=a.split("/");e=e[e.length-1];for(d in this.map._layers)this.map._layers.hasOwnProperty(d)&&(b&&this.map._layers[d].url===a&&this.map._layers[d].id===b?this.map._layers[d].setVisibility(c):this.map._layers[d].visibleLayers&&(b&&this.map._layers[d].id===
b.substring(0,b.lastIndexOf("_")))&&(f=this.map._layers[d].url[this.map._layers[d].url.length-1],f="/"===f?this.map._layers[d].url+e:this.map._layers[d].url+"/"+e,f===a&&(f=this.map._layers[d].visibleLayers,g=E.indexOf(f,parseInt(e,10)),c?-1===g&&f.push(parseInt(e,10)):-1!==g&&f.splice(g,1),this.map._layers[d].setVisibleLayers(f))))}})});