// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/event dojo/_base/lang dojo/_base/Color dojo/DeferredList dojo/dom-class dojox/gfx/fx dojo/on dojo/Evented esri/layers/GraphicsLayer esri/graphic esri/geometry/Extent esri/geometry/Point esri/symbols/PictureMarkerSymbol esri/symbols/SimpleMarkerSymbol esri/symbols/SimpleLineSymbol esri/symbols/TextSymbol esri/symbols/Font esri/renderers/SimpleRenderer esri/request esri/tasks/query esri/tasks/QueryTask esri/symbols/jsonUtils esri/layers/FeatureLayer".split(" "),
function(z,t,A,n,l,B,x,C,D,E,F,m,G,u,w,f,h,H,I,J,K,r,y,v,L){return z("ClusterLayer",[F,E],{constructor:function(a){this.clusterGraphics=null;this.cancelRequest=!1;this.clusterSize=120;this._singles=[];this._showSingles=!0;this.updateFeatures=[];if(this._parentLayer=a.parentLayer)this.objectIdField=this._parentLayer.objectIdField,this.fields=this._parentLayer.fields;this.name=a.name;this._map=a.map;this.color=l.fromString(a.color||"#ff0000");this._styleColor=a._styleColor;this.symbolData=a.lyrInfo.symbolData;
this.countColor=this.symbolData._highLightColor;this.itemId=a.lyrInfo.itemId;this.refresh=a.lyrInfo.refresh;this.displayFeatureCount=this.symbolData.displayFeatureCount;this.node=a.node;this.countEnabled=a.countEnabled;this.legendNode=a.legendNode;this.id=a.id;this.infoTemplate=a.infoTemplate;this.url=a.lyrInfo.url;this._testRenderer=a.lyrInfo.renderer;(this.originOperLayer=a.originOperLayer)&&this._getInfoTemplate(this.originOperLayer);this.lyrInfo=a.lyrInfo;this.lyrType=a.lyrType;this.filter=a.filter;
this._setupSymbols();this._setFieldNames();this.countFeatures(this._parentLayer);0<this._parentLayer.refreshInterval&&setInterval(n.hitch(this,this._updateEnd),6E4*this._parentLayer.refreshInterval)},countFeatures:function(a){var b=new r;b.geometry=this._map.extent;a.queryCount?a.queryCount(b,n.hitch(this,function(b){if(0<b)this.nodeCount=b,this._initFeatures(this._parentLayer);else{this.nodeCount=0;var d=new L(a.url);D(d,"load",n.hitch(this,function(){this.countFeatures(d)}))}})):this._initFeatures(this._parentLayer)},
_initFeatures:function(a){this._features=[];var b=!0,c=new r;-1<["CSV","Feature Collection","GeoRSS","KML"].indexOf(this.lyrType)||null===this.url?(this._getSourceFeatures(a.graphics),this.clusterFeatures()):"undefined"!==typeof this.url?this.loadData(this.url):(c.where=this.filter?this.filter:"1\x3d1",c.outFields=this._fieldNames,c.returnGeometry=!0,a.queryFeatures?a.queryFeatures(c).then(n.hitch(this,function(a){a.features&&(this._getSourceFeatures(a.features),this.clusterFeatures())})):b="error");
"error"!==b&&(this.extentChangeSignal||(this.extentChangeSignal=this._map.on("extent-change",n.hitch(this,this.handleMapExtentChange))),this.clickSignal||(this.clickSignal=this.on("click",n.hitch(this,this.handleClick))))},_getSourceFeatures:function(a){this._features=[];for(var b=0;b<a.length;b++){var c=a[b];c.geometry&&this._features.push(c)}},_getInfoTemplate:function(a){a=a.parentLayerInfo?a.parentLayerInfo:a;if(a.controlPopupInfo&&(a=a.controlPopupInfo.infoTemplates)){if(this.url){var b=this.url.split("/").pop();
b&&(a.indexOf?-1<a.indexOf(b)&&(this.infoTemplate=a[b].infoTemplate):a.hasOwnProperty(b)&&(this.infoTemplate=a[b].infoTemplate))}this.setInfoTemplate(this.infoTemplate)}},_setFieldNames:function(){this._fieldNames=[];if(this.infoTemplate&&"undefined"!==typeof this.infoTemplate.info){var a=this.infoTemplate.info.fieldInfos;if(a)for(var b=0;b<a.length;b++)a[b].visible&&this._fieldNames.push(a[b].fieldName)}if(this.symbolData.featureDisplayOptions&&0<this.symbolData.featureDisplayOptions.fields.length)for(a=
0;a<this.symbolData.featureDisplayOptions.fields.length;a++)b=this.symbolData.featureDisplayOptions.fields[a],-1===this._fieldNames.indexOf(b.name)&&this._fieldNames.push(b.name);1>this._fieldNames.length&&(this._fieldNames=["*"])},setLayerInfo:function(a){this.lyrInfo=a},clearSingles:function(a){t.forEach(a||this._singles,function(a){this.remove(a)},this);this._singles.length=0},_getSingleGraphic:function(a){a=new m(new u(a.geometry.x,a.geometry.y,this._map.spatialReference),null,a.attributes);a.setSymbol(this._singleSym);
return a},_addSingles:function(a){t.forEach(a,function(a){a=this._getSingleGraphic(a);this._singles.push(a);this._showSingles&&this.add(a)},this);this._map.infoWindow.setFeatures(this._singles)},initalCount:function(a){var b=new r;b.returnGeometry=!1;b.geometry=this._map.extent;b.where=this.filter?this.filter:"1\x3d1";(new y(a)).executeForIds(b).then(n.hitch(this,function(a){this.node&&(x.contains(this.node,"searching")&&x.remove(this.node,"searching"),this.node.innerHTML=a?a.length.toLocaleString():
0)}))},loadData:function(a){if(0<a.length){this.initalCount(a);var b=new r;b.where="1\x3d1";this.filter&&(b.where=this.filter);b.returnGeometry=!1;this.queryPending=!0;(new y(a)).executeForIds(b).then(n.hitch(this,function(b){if(b){this.queryIDs=b;b=[];var d,k;d=0;for(k=this.queryIDs.length;d<k;d+=1E3){var e=this.queryIDs.slice(d,d+1E3);b.push(K({url:a+"/query",content:{f:"json",outFields:this._fieldNames.join(),objectids:e.join(),returnGeometry:"true",outSR:this._map.spatialReference.wkid}}))}this._features=
[];this.cancelRequest?console.log("Cancelled ClusterLayer 1"):(new B(b)).then(n.hitch(this,function(a){this.queryPending=!1;if(this.cancelRequest)console.log("Cancelled ClusterLayer 2");else if(a){for(var b=this._map.spatialReference,c=[],d=0;d<a.length;d++)if(a[d][1].features)for(var e=0;e<a[d][1].features.length;e++){var k=a[d][1].features[e];if("undefined"!==typeof k.geometry){var f=new u(k.geometry.x,k.geometry.y,b),f=new m(f);f.setAttributes(k.attributes);this.infoTemplate&&f.setInfoTemplate(this.infoTemplate);
c.push(f)}}a=!0;1E4>c&&(a=JSON.stringify(this._features)!==JSON.stringify(c));a&&(this._features=c,this.clusterFeatures(),this.emit("update-end",{bubbles:!0,cancelable:!0}))}}))}}))}},handleClick:function(a){var b=[];if(a.graphic&&(b=a.graphic,b.attributes)){var c=b.attributes;c.Data&&1<c.Data.length?(this.clearSingles(this._singles),b=c.Data,a.stopPropagation(),this._addSingles(b)):this._map.infoWindow.setFeatures([b])}this.infoTemplate&&this._map.infoWindow.show(a.mapPoint);A.stop(a)},handleMapExtentChange:function(a){if(a.levelChange)this.clusterFeatures();
else if(a.delta){var b=a.delta;a=Math.abs(b.x);b=Math.abs(b.y);(50<a||50<b)&&this.clusterFeatures()}},refreshFeatures:function(a){if(this.itemId){a=a.featureSet.features;var b=!0;1E4>a.length&&(b=JSON.stringify(this.updateFeatures)!==JSON.stringify(a));if(b){this._features=[];this._parentLayer.clear();var b=this._parentLayer.spatialReference,c;this._parentLayer.renderer?c=this._parentLayer.renderer:this._testRenderer&&(c=this._testRenderer);for(var d=0;d<a.length;d++){var k=a[d];if(k.geometry){var e=
new m(this.getGraphicOptions(k,b,c));e.setAttributes(k.attributes);this.infoTemplate&&e.setInfoTemplate(this.infoTemplate);e.setSymbol(c.getSymbol(e));this._parentLayer.add(e);this._features.push(e)}else console.log("Null geometry skipped")}this.clusterFeatures()}this.updateFeatures=a}else this.url&&this.loadData(this.url)},getGraphicOptions:function(a,b,c){return"undefined"!==typeof a.geometry.rings?{geometry:{rings:a.geometry.rings,spatialReference:{wkid:b.wkid}}}:"undefined"!==typeof a.geometry.paths?
{geometry:{paths:a.geometry.paths,spatialReference:{wkid:b.wkid}}}:{geometry:new u(a.geometry.x,a.geometry.y,a.geometry.spatialReference),symbol:c.symbol}},flashFeatures:function(){this.flashGraphics(this.graphics)},flashSingle:function(a){if("undefined"===typeof a.symbol){var b=new h(h.STYLE_NULL,new l(0,0,0,0),0),c=this.color.toRgb();a.setSymbol(new f(f.STYLE_CIRCLE,9,b,new l([c[0],c[1],c[2],0.5])))}this.flashGraphics([a])},flashGraphics:function(a){for(var b=0;b<a.length;b++)this._flashFeature(a[b])},
_flashFeature:function(a){var b;if(a.geometry){b=l.fromHex(this._styleColor);var c=n.clone(b);c.a=0.4;b=new f(f.STYLE_CIRCLE,a.symbol.size,new h(h.STYLE_SOLID,b,1),c)}a=new m(a.geometry,b);this._map.graphics.add(a);if(b=a.getDojoShape())C.animateStroke({shape:b,duration:700,color:{start:b.strokeStyle.color,end:b.strokeStyle.color},width:{start:18,end:0}}).play(),setTimeout(this._clearFeature,850,a)},_clearFeature:function(a){a.getLayer().remove(a)},setColor:function(a){this.color=a},setStyleColor:function(a){this._styleColor=
a},cancelPendingRequests:function(){console.log("Cancel Query...");this.queryPending&&(this.cancelRequest=!0);this.removeEventListeners()},removeEventListeners:function(){this.extentChangeSignal&&(this.extentChangeSignal.remove(),this.extentChangeSignal=null);this.clickSignal&&(this.clickSignal.remove(),this.clickSignal=null)},clusterFeatures:function(){this.clear();this._map.infoWindow.isShowing&&this._map.infoWindow.hide();var a=this._features,b=0;if("undefined"!==typeof a){if(0<a.length){var c=
this.clusterSize;this.clusterGraphics=[];for(var d=this._map.spatialReference,k=this._map.extent,e=new u(k.xmin,k.ymax,d),g=Math.ceil(this._map.height/c),f=Math.ceil(this._map.width/c),h=k.getWidth()/this._map.width*c,c=k.getHeight()/this._map.height*c,k=0;k<g;k++)for(var n=0;n<f;n++){var l=e.x+h*n,s=e.y-c*k,s=new G(l,s-c,l+h,s,d),l=[],q;for(q in a){var r=a[q];s.contains(r.geometry)&&(b+=1,l.push(r))}0<l.length&&(s=this.getClusterCenter(l),this.clusterGraphics.push({center:s,graphics:l}))}for(var t in this.clusterGraphics){a=
this.clusterGraphics[t];d=a.graphics.length;e=a.graphics;h=d.toString();f=g=19*h.length;g+=5;q=new I;q.family="Arial";q.size="16px";h=new H(h,q,this.countColor);h.setOffset(0,-4);var p;this.symbolData&&this.symbolData.symbol?this.symbolData.symbol.size?p=this.symbolData.symbol.size:this.symbolData.symbol.width&&(p=this.symbolData.symbol.width,q=this.symbolData.symbol.height,p=p>=q?p:q):this.icon.width?(g=this.icon.width>=g?this.icon.width+5:g,g=this.icon.height>=g?this.icon.height+5:g,f=this.icon.width>=
f?this.icon.width+1:f,f=this.icon.height>=f?this.icon.height+1:f):this.icon.size&&(p=this.icon.size);p&&(g=p>=g?p+5:g,f=p>=f?p+1:f);f>=g&&(g+=0===f-g?4:f-g+5);this._setSymbols(g+15,g);e={Count:d,Data:e};1<d?"undefined"!==typeof this.symbolData?"CustomSymbol"!==this.symbolData.symbolType?(this.add(new m(a.center,this.csym,e)),this.displayFeatureCount?this.add(new m(a.center,h,e)):this.add(new m(a.center,this.csym3,e))):(this.add(new m(a.center,this.csym,e)),this.displayFeatureCount?this.add(new m(a.center,
h,e)):this.add(new m(a.center,this.psym,e))):(this.add(new m(a.center,this.csym,e)),this.displayFeatureCount?this.add(new m(a.center,h,e)):this.add(new m(a.center,this.psym,e))):(a=a.graphics[0].geometry,this.renderer&&(this.renderer.hasOwnProperty("getSymbol")&&"LayerSymbol"===this.symbolData.symbolType?(a=new m(a,null,e.Data[0].attributes),d=this.renderer.getSymbol(a),a.setInfoTemplate(this.infoTemplate),a.setSymbol(d),this.add(a)):this.renderer.hasOwnProperty("symbol")&&"LayerSymbol"===this.symbolData.symbolType?
(a=new m(a,null,e.Data[0].attributes),a.setInfoTemplate(this.infoTemplate),a.setSymbol(v.fromJson(this.renderer.symbol)),this.add(a)):"EsriSymbol"===this.symbolData.symbolType?this.add(new m(a,v.fromJson(this.symbolData.symbol),e)):"LayerSymbol"!==this.symbolData.symbolType?this.add(new m(a,this.psym,e)):(a=this.renderer.symbol?new m(a,this.renderer.symbol,e):new m(a,this.psym,e),a.setInfoTemplate(this.infoTemplate),this.add(a))))}}this._updateNode(b)}},_updateNode:function(a){this.node&&(this.node.innerHTML=
a?a.toLocaleString():0)},_updatePanelTime:function(a){this.pageTitle.innerHTML="\x3cdiv\x3e\x3c/div\x3e";var b="";""!==this.config.mainPanelText&&(b=this.config.mainPanelText+" ");this.pageTitle.innerHTML=b+(new Date(a)).toLocaleDateString(navigator.language,{month:"2-digit",day:"2-digit",year:"numeric",hour:"numeric",minute:"2-digit",hour12:!0})},_setSymbols:function(a,b){var c=this.color.toRgb(),d,k,e;if("undefined"!==typeof this.symbolData){var g;"custom"===this.backgroundClusterSymbol?g=c:(d=
v.fromJson(this.backgroundClusterSymbol),0===d.outline.color.a||0===d.outline.width?(k=h.STYLE_NULL,e=0):(k=h.STYLE_SOLID,e=d.outline.width));d?(c=h(k,d.outline.color,e),g=d.color.toRgb(),this.csym=new f(f.STYLE_CIRCLE,a,c,new l([g[0],g[1],g[2],0.75]))):this.csym=new f(f.STYLE_CIRCLE,a,null,new l([g[0],g[1],g[2],0.75]));c=this.symbolData.s;(c=-1<c.indexOf("${appPath}")?this.symbolData.s.replace("${appPath}",window.location.origin+window.location.pathname):this.symbolData.s?this.symbolData.s:this.icon.imageData)&&
"CustomIcon"===this.symbolData.iconType?this.psym=new w(c,a-6,a-6):c&&"LayerIcon"===this.symbolData.iconType?this.psym=v.fromJson(this.symbolData.symbol):(c=h(this.icon.outline.style,this.icon.outline.color,this.icon.outline.width),this.psym=new f(this.icon.style,this.icon.size,c,this.icon.color));this.csym2=n.clone(this.psym);this.csym3=n.clone(this.csym2);"undefined"!==typeof this.csym2.xoffset&&(this.csym3.xoffset=0);"undefined"!==typeof this.csym2.yoffset&&(this.csym3.yoffset=0)}else d=new h(h.STYLE_NULL,
new l(0,0,0,0),0),this.csym=new f(f.STYLE_CIRCLE,a,d,new l([c[0],c[1],c[2],0.5])),this.psym=new w(this.icon.url,a-10,a-10),this.psym2=new w(this.icon.url,b-7,b-7),d=new h(h.STYLE_NULL,new l(0,0,0,0),0),this.csym2=new f(f.STYLE_CIRCLE,b,d,new l([c[0],c[1],c[2],0.5]))},_setupSymbols:function(){if("undefined"!==typeof this.symbolData){this.countColor=this.symbolData._highLightColor;this.backgroundClusterSymbol=this.symbolData.clusterSymbol;this.icon=this.symbolData.icon;"LayerSymbol"===this.symbolData.symbolType?
this._parentLayer.renderer?this.renderer=this._parentLayer.renderer:this.symbolData.renderer&&(this.renderer=this._testRenderer):this.renderer=new J(v.fromJson(this.symbolData.symbol));var a=this.color.toRgb(),b=new h(h.STYLE_NULL,new l(0,0,0,0),0);this._singleSym=new f(f.STYLE_CIRCLE,9,b,new l([a[0],a[1],a[2],0.5]))}},getLayer:function(){return this},getClusterCenter:function(a){var b=0,c=0,d=a.length;t.forEach(a,function(a){b+=a.geometry.x;c+=a.geometry.y},this);return new u(b/d,c/d,a[0].geometry.spatialReference)},
destroy:function(){this._clear();this.removeEventListeners()},_clear:function(){this.clear();this._features=[]},_updateEnd:function(){this.loadData(this.url)}})});