// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo/_base/declare dojo/_base/array dojo/_base/lang dojo/Deferred dojo/promise/all jimu/portalUrlUtils jimu/WidgetManager esri/lang esri/graphicsUtils ./NlsStrings".split(" "),function(n,k,d,l,p,m,q,f,r,s){var h=n([],{_candidateMenuItems:null,_displayItems:null,_layerInfo:null,_layerType:null,_appConfig:null,constructor:function(a,b,c,g){this.nls=s.value;this._layerInfo=a;this._layerType=c;this.layerListWidget=g;this._initCandidateMenuItems();this._initDisplayItems(b)},_getATagLabel:function(){var a,
b;a=this._layerInfo._isItemLayer&&this._layerInfo._isItemLayer();b=this._layerInfo.getUrl();a?(a=m.getItemDetailsPageUrl(m.getStandardPortalUrl(this.layerListWidget.appConfig.portalUrl),a),b=this.nls.itemShowItemDetails):b&&("CSVLayer"===this._layerType||"KMLLayer"===this._layerType)?(a=b,b=this.nls.itemDownload):(a=b&&"WMSLayer"===this._layerType?b+(-1<b.indexOf("?")?"\x26":"?")+"SERVICE\x3dWMS\x26REQUEST\x3dGetCapabilities":b&&"WFSLayer"===this._layerType?b+(-1<b.indexOf("?")?"\x26":"?")+"SERVICE\x3dWFS\x26REQUEST\x3dGetCapabilities":
b?b:"",b=this.nls.itemDesc);return'\x3ca class\x3d"menu-item-description" target\x3d"_blank" href\x3d"'+a+'"\x3e'+b+"\x3c/a\x3e"},_initCandidateMenuItems:function(){this._candidateMenuItems=[{key:"separator",label:""},{key:"empty",label:this.nls.empty},{key:"zoomto",label:this.nls.itemZoomTo},{key:"transparency",label:this.nls.itemTransparency},{key:"moveup",label:this.nls.itemMoveUp},{key:"movedown",label:this.nls.itemMoveDown},{key:"table",label:this.nls.itemToAttributeTable},{key:"controlPopup",
label:this.nls.removePopup},{key:"url",label:this._getATagLabel()}]},_initDisplayItems:function(a){this._displayItems=[];k.forEach(a,function(b){k.forEach(this._candidateMenuItems,function(a){b.key===a.key&&(this._displayItems.push(d.clone(a)),b.onClick&&(this._displayItem.onClick=b.onClick))},this)},this)},getDeniedItems:function(){var a=new l,b=[];this.layerListWidget.layerListView.isFirstDisplayedLayerInfo(this._layerInfo)&&b.push({key:"moveup",denyType:"disable"});this.layerListWidget.layerListView.isLastDisplayedLayerInfo(this._layerInfo)&&
b.push({key:"movedown",denyType:"disable"});this._layerInfo.getUrl()||b.push({key:"url",denyType:"disable"});var c=this._layerInfo.loadInfoTemplate(),g=this._layerInfo.getSupportTableInfo();p({infoTemplate:c,supportTableInfo:g}).then(d.hitch(this,function(c){c.infoTemplate||b.push({key:"controlPopup",denyType:"disable"});c=c.supportTableInfo;var e=this.layerListWidget.appConfig.getConfigElementsByName("AttributeTable")[0];if(!e||!e.visible)b.push({key:"table",denyType:"hidden"});else if(!c.isSupportedLayer||
!c.isSupportQuery||c.otherReasonCanNotSupport)this._layerInfo.parentLayerInfo&&this._layerInfo.parentLayerInfo.isMapNotesLayerInfo()?b.push({key:"table",denyType:"hidden"}):b.push({key:"table",denyType:"disable"});a.resolve(b)}),function(){a.resolve(b)});return a},getDisplayItems:function(){return this._displayItems},onPopupMenuClick:function(a){var b={closeMenu:!0};switch(a.itemKey){case "zoomto":this._onItemZoomToClick(a);break;case "moveup":this._onMoveUpItemClick(a);break;case "movedown":this._onMoveDownItemClick(a);
break;case "table":this._onTableItemClick(a);break;case "transparencyChanged":this._onTransparencyChanged(a);b.closeMenu=!1;break;case "controlPopup":this._onControlPopup()}return b},_onItemZoomToClick:function(a){this._layerInfo.getExtent().then(d.hitch(this,function(b){var a=null;b=b&&0<b.length&&b[0];this._isValidExtent(b)&&(a=b);a?this._layerInfo.map.setExtent(a):0<=this._layerInfo.map.graphicsLayerIds.indexOf(this._layerInfo.id)&&this._layerInfo.getLayerObject().then(d.hitch(this,function(b){if(b.graphics&&
0<b.graphics.length){try{a=r.graphicsExtent(b.graphics)}catch(d){console.error(d)}a&&this._layerInfo.map.setExtent(a)}}))}))},_isValidExtent:function(a){var b=!1;f.isDefined(a)&&f.isDefined(a.xmin)&&(isFinite(a.xmin)&&f.isDefined(a.ymin)&&isFinite(a.ymin)&&f.isDefined(a.xmax)&&isFinite(a.xmax)&&f.isDefined(a.ymax)&&isFinite(a.ymax))&&(b=!0);return b},_onMoveUpItemClick:function(a){this._layerInfo.isFirst||a.layerListView.moveUpLayer(this._layerInfo)},_onMoveDownItemClick:function(a){this._layerInfo.isLast||
a.layerListView.moveDownLayer(this._layerInfo)},_onTableItemClick:function(a){this._layerInfo.getSupportTableInfo().then(d.hitch(this,function(b){if(b.isSupportedLayer&&b.isSupportQuery){b=q.getInstance();var c=this.layerListWidget.appConfig.getConfigElementsByName("AttributeTable")[0];b.triggerWidgetOpen(c.id).then(d.hitch(this,function(){a.layerListWidget.publishData({target:"AttributeTable",layer:this._layerInfo})}))}}))},_onTransparencyChanged:function(a){this._layerInfo.setOpacity(1-a.extraData.newTransValue)},
_onControlPopup:function(a){this._layerInfo.controlPopupInfo.enablePopup?this._layerInfo.disablePopup():this._layerInfo.enablePopup();this._layerInfo.map.infoWindow.hide()}});h.create=function(a,b){var c=new l,g=a.isRootLayer(),f={RootLayer:[{key:"zoomto"},{key:"transparency"},{key:"separator"},{key:"moveup"},{key:"movedown"},{key:"separator"},{key:"url"}],RootLayerAndFeatureLayer:[{key:"zoomto"},{key:"transparency"},{key:"separator"},{key:"controlPopup"},{key:"separator"},{key:"moveup"},{key:"movedown"},
{key:"separator"},{key:"table"},{key:"separator"},{key:"url"}],FeatureLayer:[{key:"controlPopup"},{key:"separator"},{key:"table"},{key:"separator"},{key:"url"}],GroupLayer:[{key:"url"}],Table:[{key:"table"},{key:"separator"},{key:"url"}],"default":[{key:"url",onClick:null}]};a.getLayerType().then(d.hitch(this,function(e){var d="",d=g&&("FeatureLayer"===e||"CSVLayer"===e||"ArcGISImageServiceLayer"===e||"StreamLayer"===e||"ArcGISImageServiceVectorLayer"===e)?"RootLayerAndFeatureLayer":g?"RootLayer":
"FeatureLayer"===e||"CSVLayer"===e?"FeatureLayer":"GroupLayer"===e?"GroupLayer":"Table"===e?"Table":"default";c.resolve(new h(a,f[d],e,b))}),d.hitch(this,function(){c.resolve(new h(a,[{key:"empty"}]))}));return c};return h});