// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
define("dojo dojo/_base/declare dojo/_base/lang dojo/_base/array dojo/dom-class dojo/query dijit/registry jimu/filterUtils jimu/BaseWidgetSetting".split(" "),function(n,p,m,f,b,l,q,r,s){return p([s],{_attrInspector:null,_fieldValidation:null,_feature:null,_fieldInfo:null,_gdbRequiredFields:null,_notEditableFields:null,_fieldNameToAlias:null,_fieldsWithRules:null,_attTable:null,_filterUtils:null,_mapLayer:null,OPERATORS:null,constructor:function(){this.inherited(arguments);m.mixin(this,arguments[0]);
this._mapLayer=this._feature.getLayer();this._processLayer();this._filterUtils=new r;this.OPERATORS=m.clone(this._filterUtils.OPERATORS);this._attTable=l("td.atiLabel",this._attrInspector.domNode);void 0===this._attTable||null===this._attTable||this._bindEvents()},_processLayer:function(){this._gdbRequiredFields=[];this._notEditableFields=[];this._fieldsWithRules=[];f.forEach(this._fieldInfo,function(b){!1===b.nullable&&!0===b.isEditable&&this._gdbRequiredFields.push(b.label);(!1===b.isEditable||
!1===b.isEditableSettingInWebmap)&&this._notEditableFields.push(b.label);this._fieldValidation&&this._fieldValidation.hasOwnProperty(b.fieldName)&&this._fieldsWithRules.push(b.label)},this)},toggleFields:function(){if(!(void 0===this._attTable||null===this._attTable))if(!(void 0===this._fieldValidation||null===this._fieldValidation))if(!(void 0===this._feature||null===this._feature)){var b=null,a=[],c;f.forEach(this._fieldInfo,m.hitch(this,function(d){b=null;c=this.validateField(d.fieldName);b=c[1];
!1===c[2]&&a.push({fieldName:d.fieldName});!0===c[0]&&this.toggleFieldOnAttributeInspector(d.label,b,c[2])}));return a}},validateField:function(b){var a=null;if(this._fieldValidation.hasOwnProperty(b)){if(0===this._fieldValidation[b].length)return[!1,null,!0];var c=[!1,null,null];f.some(this._fieldValidation[b],function(d){if(void 0!==d.filter&&null!==d.filter&&(a=d.filter,c=[!0,null,null],this.processFilter(a,this._feature)))return"Required"===d.actionName?!1===this._feature.attributes.hasOwnProperty(b)?
(c=[!0,d.actionName,!1],!0):null===this._feature.attributes[b]||""===this._feature.attributes[b]?(c=[!0,d.actionName,!1],!0):(c=[!0,d.actionName,!0],!0):(c=[!0,d.actionName,null,d.submitWhenHidden],!0)},this);return c}return[!1,null,null]},_bindEvents:function(){void 0===this._attTable||null===this._attTable||0<this._attTable.length&&f.forEach(this._attTable,function(b){b=this._getRowInfo(b);-1!==this._fieldsWithRules.indexOf(b[3])&&"dijit.form.FilteringSelect"===b[2].declaredClass&&n.connect(b[2],
"onChange",m.hitch(this,this._smartComboValidate()))},this)},processFilter:function(b){var a=[];f.forEach(b.parts,function(c){if(c.hasOwnProperty("parts"))a.push(this.processFilter(c,this._feature));else{var b=null,g=null;c.valueObj.hasOwnProperty("value")&&(b=c.valueObj.value);c.valueObj.hasOwnProperty("value1")&&(b=c.valueObj.value1);c.valueObj.hasOwnProperty("value2")&&(g=c.valueObj.value2);switch(c.valueObj.type){case "value":case "unique":a.push(this.validatePart(c.operator,this._feature.attributes[c.fieldObj.name],
b,g,c.caseSensitive));break;case "field":a.push(this.validatePart(c.operator,this._feature.attributes[c.fieldObj.name],b,g,c.caseSensitive))}}},this);return this.ruleValid(a,b.logicalOperator)},ruleValid:function(b,a){var c=!1;if(void 0===a||null===a)a="OR";f.some(b,function(b){if("OR"===a){if(!0===b)return c=!0;c=!1}else{if(!1===b)return c=!1,!0;c=!0}});return c},_isNumeric:function(b){return!isNaN(parseFloat(b))&&isFinite(b)},validatePart:function(b,a,c,d,e){var h=null;if(void 0===b||null===b)return!1;
0===b.lastIndexOf("string",0)?!1===e&&(void 0!==a&&null!==a&&(a=String(a).toUpperCase()),void 0!==c&&null!==c&&(c=String(c).toUpperCase()),void 0!==d&&null!==d&&(d=String(d).toUpperCase())):0===b.lastIndexOf("date",0)&&(void 0!==c&&null!==c&&(c=new Date(c)),void 0!==d&&null!==d&&(d=new Date(d)));switch(b){case this.OPERATORS.stringOperatorIs:if(a===c)return!0;break;case this.OPERATORS.stringOperatorIsNot:if(a!==c)return!0;break;case this.OPERATORS.stringOperatorStartsWith:if(null===a&&null===c)return!0;
if(null===a&&null!==c)break;if(null!==a&&null===c)break;if(0===a.lastIndexOf(c,0))return!0;break;case this.OPERATORS.stringOperatorEndsWith:if(null===a&&null===c)return!0;if(null===a&&null!==c)break;if(null!==a&&null===c)break;return this._endsWith(a,c);case this.OPERATORS.stringOperatorContains:if(null===a&&null===c)return!0;if(null===a&&null!==c)break;if(null!==a&&null===c)break;if(String(a).indexOf(0<=c))return!0;break;case this.OPERATORS.stringOperatorDoesNotContain:if(null===a&&null===c)break;
if(null===a&&null!==c||null!==a&&null===c)return!0;String(a).indexOf(0<=c);break;case this.OPERATORS.stringOperatorIsBlank:return void 0===a||null===a||""===a;case this.OPERATORS.stringOperatorIsNotBlank:return void 0!==a&&null!==a&&""!==a;case this.OPERATORS.numberOperatorIs:if(this._isNumeric(a))return String(a)===String(c);break;case this.OPERATORS.numberOperatorIsNot:if(this._isNumeric(a))return String(a)!==String(c);break;case this.OPERATORS.numberOperatorIsAtLeast:if(this._isNumeric(a)&&this._isNumeric(c))return a>=
c;break;case this.OPERATORS.numberOperatorIsLessThan:if(this._isNumeric(a)&&this._isNumeric(c))return a<c;break;case this.OPERATORS.numberOperatorIsAtMost:if(this._isNumeric(a)&&this._isNumeric(c))return a<=c;break;case this.OPERATORS.numberOperatorIsGreaterThan:if(this._isNumeric(a)&&this._isNumeric(c))return a>c;break;case this.OPERATORS.numberOperatorIsBetween:if(this._isNumeric(a)&&this._isNumeric(c)&&this._isNumeric(d))return a>c&&a<d;break;case this.OPERATORS.numberOperatorIsNotBetween:if(this._isNumeric(a)&&
this._isNumeric(c)&&this._isNumeric(d))return a<=c||a>=d;break;case this.OPERATORS.numberOperatorIsBlank:if(null===a||void 0===a)return!0;break;case this.OPERATORS.numberOperatorIsNotBlank:if(null!==a&&void 0!==a)return!0;break;case this.OPERATORS.dateOperatorIsOn:if(void 0===a||null===a)break;if(void 0===c||null===c)break;h=new Date(a);return c.toDateString()===h.toDateString();case this.OPERATORS.dateOperatorIsNotOn:if(void 0===a||null===a)break;if(void 0===c||null===c)break;h=new Date(a);return c.toDateString()!==
h.toDateString();case this.OPERATORS.dateOperatorIsBefore:if(null===a||void 0===a)break;if(void 0===c||null===c)break;return a<c.getTime();case this.OPERATORS.dateOperatorIsAfter:if(null===a||void 0===a)break;if(void 0===c||null===c)break;return a>c.getTime();case this.OPERATORS.dateOperatorIsBetween:if(null===a||void 0===a)break;if(void 0===c||null===c)break;if(void 0===d||null===d)break;return a>c.getTime()&&a<d.getTime();case this.OPERATORS.dateOperatorIsNotBetween:if(null===a||void 0===a)break;
if(void 0===c||null===c)break;if(void 0===d||null===d)break;return a<=c.getTime()||a>=d.getTime();case this.OPERATORS.dateOperatorIsBlank:if(null===a||void 0===a)return!0;break;case this.OPERATORS.dateOperatorIsNotBlank:if(null!==a&&void 0!==a)return!0}return!1},_processChildNodes:function(b,a){b.disabled=a;b.style.pointerEvents=!0===a?"none":"auto";f.forEach(b.childNodes,function(b){b.disabled=a;b.style.pointerEvents=!0===a?"none":"auto";0<b.childNodes.length&&this._processChildNodes(b,a)},this)},
_smartComboValidate:function(){this.toggleFields()},_getRowInfo:function(b){var a=b.parentNode.childNodes[1].childNodes[0],c=null;1<b.parentNode.childNodes[1].childNodes.length&&(c=b.parentNode.childNodes[1].childNodes[1]);var d=b.childNodes[0].data;b=b.parentNode;var e=q.getEnclosingWidget(a);return[a,b,e,d,c]},_removeRequireFieldMarkings:function(g,a,c,d){var e=null;-1===this._gdbRequiredFields.indexOf(g)&&(void 0===d||null===d?(b.contains(a,"dijitComboBoxError")&&b.remove(a,"dijitComboBoxError"),
b.contains(a,"dijitTextBoxError")&&b.remove(a,"dijitTextBoxError"),b.contains(a,"dijitValidationTextBox")&&b.remove(a,"dijitValidationTextBox"),b.contains(a,"dijitValidationTextBoxError")&&b.remove(a,"dijitValidationTextBoxError"),b.contains(a,"dijitError")&&b.remove(a,"dijitError"),e=l(".dijitValidationContainer",c),f.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.TextBox"===d.declaredClass?(b.contains(a,"dijitTextBoxError")&&b.remove(a,"dijitTextBoxError"),b.contains(a,"dijitValidationTextBox")&&
b.remove(a,"dijitValidationTextBox"),b.contains(a,"dijitValidationTextBoxError")&&b.remove(a,"dijitValidationTextBoxError"),b.contains(a,"dijitError")&&b.remove(a,"dijitError"),e=l(".dijitValidationContainer",c),f.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.ValidationTextBox"===d.declaredClass?(b.contains(a,"dijitTextBoxError")&&b.remove(a,"dijitTextBoxError"),b.contains(a,"dijitTextBoxDisabled")&&b.remove(a,"dijitTextBoxDisabled"),b.contains(a,"dijitValidationTextBoxError")&&
b.remove(a,"dijitValidationTextBoxError"),b.contains(a,"dijitError")&&b.remove(a,"dijitError")):"dijit.form.DateTextBox"===d.declaredClass?(b.contains(a,"dijitTextBoxError")&&b.remove(a,"dijitTextBoxError"),b.contains(a,"dijitValidationTextBox")&&b.remove(a,"dijitValidationTextBox"),b.contains(a,"dijitValidationTextBoxError")&&b.remove(a,"dijitValidationTextBoxError"),b.contains(a,"dijitError")&&b.remove(a,"dijitError"),e=l(".dijitValidationContainer",c),f.forEach(e,function(a){a.parentNode.removeChild(a)})):
"dijit.form.TimeTextBox"===d.declaredClass?(b.contains(a,"dijitTextBoxError")&&b.remove(a,"dijitTextBoxError"),b.contains(a,"dijitValidationTextBox")&&b.remove(a,"dijitValidationTextBox"),b.contains(a,"dijitValidationTextBoxError")&&b.remove(a,"dijitValidationTextBoxError"),b.contains(a,"dijitError")&&b.remove(a,"dijitError"),e=l(".dijitValidationContainer",c),f.forEach(e,function(a){a.parentNode.removeChild(a)})):"dijit.form.FilteringSelect"===d.declaredClass?(b.contains(a,"dijitTextBoxError")&&
b.remove(a,"dijitTextBoxError"),b.contains(a,"dijitComboBoxError")&&b.remove(a,"dijitComboBoxError"),b.contains(a,"dijitError")&&b.remove(a,"dijitError"),b.contains(a,"dijitValidationTextBoxError")&&b.remove(a,"dijitValidationTextBoxError")):(b.contains(a,"dijitComboBoxError")&&b.remove(a,"dijitComboBoxError"),b.contains(a,"dijitTextBoxError")&&b.remove(a,"dijitTextBoxError"),b.contains(a,"dijitValidationTextBox")&&b.remove(a,"dijitValidationTextBox"),b.contains(a,"dijitValidationTextBoxError")&&
b.remove(a,"dijitValidationTextBoxError"),b.contains(a,"dijitError")&&b.remove(a,"dijitError"),e=l(".dijitValidationContainer",c),f.forEach(e,function(a){a.parentNode.removeChild(a)})))},_removeRedAst:function(b,a){if(-1===this._gdbRequiredFields.indexOf(a)){var c=l("a.asteriskIndicator",b);0<c.length&&f.forEach(c,function(a){a.parentNode.removeChild(a)})}},_removeHideRule:function(g){b.contains(g,"hideField")&&b.remove(g,"hideField")},_removeDisableRule:function(g,a){-1===this._notEditableFields.indexOf(g)&&
(b.contains(a,"dijitTextBoxDisabled")&&b.remove(a,"dijitTextBoxDisabled"),b.contains(a,"dijitComboBoxDisabled")&&b.remove(a,"dijitComboBoxDisabled"),b.contains(a,"dijitValidationTextBoxDisabled")&&b.remove(a,"dijitValidationTextBoxDisabled"),b.contains(a,"dijitDisabled")&&b.remove(a,"dijitDisabled"));this._processChildNodes(a,!1)},_remove:function(b,a,c,d,e){this._removeRequireFieldMarkings(a,c,d,e);this._removeRedAst(b[0],a);this._removeDisableRule(a,c);this._removeHideRule(d)},toggleFieldOnAttributeInspector:function(g,
a,c){if(void 0===this._gdbRequiredFields||null===this._gdbRequiredFields)this._gdbRequiredFields=[];if(void 0===this._notEditableFields||null===this._notEditableFields)this._notEditableFields=[];if(!(void 0===this._attTable||null===this._attTable)&&0<this._attTable.length){var d=n.filter(this._attTable,m.hitch(this,function(a){return a.childNodes&&0<a.childNodes.length&&a.childNodes[0].data?a.childNodes[0].data===g:!1})),e=null;if(null!==d&&0<d.length){var h=this._getRowInfo(d[0]),k=h[0],e=h[4],f=
h[1],h=h[2];if(void 0===h||null===h)console.log(d[0]);else switch(a){case "Hide":this._removeRequireFieldMarkings(g,k,f,h);this._removeRedAst(d[0],g);this._removeDisableRule(g,k);b.add(f,"hideField");break;case "Disabled":this._removeRedAst(d[0],g);this._removeHideRule(f);this._removeRequireFieldMarkings(g,k,f,h);b.add(k,["dijitValidationTextBox","dijitTextBoxDisabled","dijitComboBoxDisabled","dijitValidationTextBoxDisabled","dijitDisabled"]);this._processChildNodes(k,!0);null!==e&&(this._removeRequireFieldMarkings(g,
e,f,h),b.add(e,["dijitValidationTextBox","dijitTextBoxDisabled","dijitComboBoxDisabled","dijitValidationTextBoxDisabled","dijitDisabled"]),this._processChildNodes(e,!0));break;case "Required":this._removeDisableRule(g,k);this._removeHideRule(f);!0===c?this._removeRequireFieldMarkings(g,k,f,h):"dijit.form.TextBox"===h.declaredClass?(e=l(".dijitValidationContainer",f),0===e.length&&(a=document.createElement("div"),a.setAttribute("class","dijitReset dijitValidationContainer"),c=document.createElement("input"),
c.setAttribute("class","dijitReset dijitInputField dijitValidationIcon dijitValidationInner"),c.setAttribute("value","x"),c.setAttribute("type","text"),c.setAttribute("tabindex","-1"),c.setAttribute("readonly","readonly"),c.setAttribute("role","presentation"),a.appendChild(c),k.insertBefore(a,k.childNodes[0])),b.add(k,["dijitTextBoxError","dijitValidationTextBox","dijitValidationTextBoxError","dijitError"])):"dijit.form.ValidationTextBox"===h.declaredClass?(e=l(".dijitValidationContainer",f),b.add(k,
["dijitTextBoxError","dijitValidationTextBox","dijitValidationTextBoxError","dijitError"])):"dijit.form.FilteringSelect"===h.declaredClass?b.add(k,["dijitTextBoxError","dijitComboBoxError","dijitError","dijitValidationTextBoxError"]):b.add(k,["dijitTextBoxError","dijitError"]);0===l("a.asteriskIndicator",d[0]).length&&(k=document.createElement("a"),k.setAttribute("class","asteriskIndicator"),k.innerHTML=" *",d[0].appendChild(k));break;case "Value":break;default:this._remove(d,g,k,f,h)}}}}})});