// All material copyright ESRI, All Rights Reserved, unless otherwise specified.
// See http://js.arcgis.com/3.15/esri/copyright.txt and http://www.arcgis.com/apps/webappbuilder/copyright.txt for details.
//>>built
require({cache:{"widgets/AttributeTable/utils":function(){define("dojo/_base/lang dojo/_base/array jimu/LayerInfos/LayerInfos dojo/Deferred dojo/promise/all exports dojo/store/Observable dojo/store/Cache dojo/store/Memory esri/lang ./table/FeatureLayerQueryStore jimu/utils".split(" "),function(f,l,t,p,e,c,m,v,d,k,u,q){function r(b,a){if(!b||!b.length)return a||[];if(!a||!a.length)return b;for(var h=[],g=0,n=b.length;g<n;g++)for(var s=b[g],e=0,c=a.length;e<c;e++)if(a[e].name===s.name){h.push(s);break}return h}
c.readLayerInfosObj=function(b){return t.getInstance(b,b.itemInfo)};c.readLayerInfosFromMap=function(b,a,h){var g=new p;t.getInstance(b,b.itemInfo).then(f.hitch(this,function(b){var s=[];a?b.traversalLayerInfosOfWebmap(function(a){s.push(a)}):b.traversal(function(a){s.push(a)});if(h){var e=[],c=b.getMapNotesLayerInfoArray();l.forEach(c,function(a){e.push(a.id);a.traversal(function(a){e.push(a.id)})});s=l.filter(s,function(a){return-1===e.indexOf(a.id)})}b=b.getTableInfoArray();s=s.concat(b);g.resolve(s)}),
f.hitch(this,function(a){console.error(a);g.reject(a)}));return g.promise};c.generateColumnsFromFields=function(b,a,h,g,n,e){function m(a){if(b&&k.isDefined(b.fieldInfos))for(var g=0,h=b.fieldInfos.length;g<h;g++){var n=b.fieldInfos[g];if(n.fieldName===a)return n.format}return null}var d={selectionHandle:{label:"",className:"selection-handle-column",hidden:!1,unhidable:!0,filed:"selection-handle-column",sortable:!1,_cache:{sortable:!1,statistics:!1}}};l.forEach(a,f.hitch(c,function(a,b,q){b="field"+
b;var v=!!a.domain,p="esriFieldTypeDate"===a.type,u=h&&a.name===h,r="esriFieldTypeDouble"===a.type||"esriFieldTypeSingle"===a.type||"esriFieldTypeInteger"===a.type||"esriFieldTypeSmallInteger"===a.type,t="esriFieldTypeString"===a.type;d[b]={label:a.alias||a.name,className:b,hidden:1===q.length?!1:!a.show&&k.isDefined(a.show),unhidable:1===q.length?!1:!a.show&&k.isDefined(a.show)&&a._pk,field:a.name,sortable:!1,_cache:{sortable:!!n,statistics:e&&!v&&r}};t?d[b].formatter=f.hitch(c,c.urlFormatter):p?
d[b].formatter=f.hitch(c,c.dateFormatter,m(a.name)):r&&(d[b].formatter=f.hitch(c,c.numberFormatter,m(a.name)));v?d[b].get=f.hitch(c,function(a,g){return this.getCodeValue(a.domain,g[a.name])},a):u?d[b].get=f.hitch(c,function(a,g,b){return this.getTypeName(b[a.name],g)},a,g):!v&&(!p&&!u)&&(d[b].get=f.hitch(c,function(a,g,b,h){var n=null;g&&b&&0<b.length&&(b=(b=l.filter(b,f.hitch(c,function(a){return a.name===h[g]})))&&b[0]||null)&&(b.domains&&b.domains[a.name]&&b.domains[a.name].codedValues)&&(n=this.getCodeValue(b.domains[a.name],
h[a.name]));return(a=null!==n?n:h[a.name])||isFinite(a)?a:""},a,h,g))}));return d};c.getTypeName=function(b,a){return q.fieldFormatter.getTypeName(b,a)};c.getCodeValue=function(b,a){return q.fieldFormatter.getCodedValue(b,a)};c.urlFormatter=function(b){return q.fieldFormatter.getFormattedUrl(b)};c.dateFormatter=function(b,a){return q.fieldFormatter.getFormattedDate(a,b)};c.numberFormatter=function(b,a){return q.fieldFormatter.getFormattedNumber(a,b)};c.readLayerObjectsFromMap=function(b,a,h){var g=
new p,n=[];this.readLayerInfosFromMap(b,a,h).then(f.hitch(this,function(a){l.forEach(a,f.hitch(this,function(a){n.push(a.getLayerObject())}));e(n).then(f.hitch(this,function(a){g.resolve(a)}),f.hitch(this,function(a){g.reject(a);console.error(a)}))}),f.hitch(this,function(a){g.reject(a)}));return g.promise};c.readSupportTableInfoFromLayerInfos=function(b){var a=new p,h=[];l.forEach(b,f.hitch(this,function(a){h.push(a.getSupportTableInfo())}));e(h).then(f.hitch(this,function(g){g=f.clone(g);l.forEach(g,
function(a,g){a.id=b[g].id});a.resolve(g)}),function(b){a.reject(b)});return a.promise};c.readConfigLayerInfosFromMap=function(b,a,h){var g=new p,n=[];this.readLayerInfosFromMap(b,a,h).then(f.hitch(this,function(a){var b=[];l.forEach(a,function(a){n.push(a.getSupportTableInfo())});e(n).then(f.hitch(this,function(h){l.forEach(h,f.hitch(this,function(g,h){g.isSupportedLayer&&(a[h].name=a[h].title,b.push(a[h]))}));g.resolve(b)}),f.hitch(this,function(a){g.reject(a)}))}),f.hitch(this,function(a){g.reject(a)}));
return g.promise};c.getConfigInfosFromLayerInfos=function(b){return l.map(b,function(a){return c.getConfigInfoFromLayerInfo(a)})};c.getConfigInfoFromLayerInfo=function(b){var a={};a.name=b.name||b.title;a.id=b.id;a.show=b.isShowInMap();a.layer={url:b.getUrl()};var h=b.getPopupInfo();h&&!h.description&&(a.layer.fields=l.map(h.fieldInfos,function(a){return{name:a.fieldName,alias:a.label,show:a.visible,format:a.format}}),b=f.getObject("layerObject.fields",!1,b),a.layer.fields=r(a.layer.fields,b),l.some(a.layer.fields,
function(a){return a.show})||(a.layer.fields[0].show=!0));return a};c.generateCacheStore=function(b,a,h,g,n){b=new u({layer:b,objectIds:b._objectIds||null,totalCount:a,batchCount:h,where:g||"1\x3d1",spatialFilter:n});a=new d;return new v(b,a,{})};c.generateMemoryStore=function(b,a){return new m(new d({data:b||[],idProperty:a}))};c.merge=function(b,a,h,g){for(var n=l.map(a,function(a){return a[h]}),e=0,c=b.length;e<c;e++){var m=n.indexOf(b[e][h]);-1<m&&g(b[e],a[m])}};c.syncOrderWith=function(b,a,h){function g(a,
b){return l.map(a,function(a){return a[b]})}if(!f.isArray(a)||!h)return b;for(var n=g(b,h),e=[],c=0,m=a.length;c<m;c++){var d=n.indexOf(a[c][h]);-1<d&&(e=e.concat(b.splice(d,1)),n=g(b,h))}return e.concat(b)}})},"dojo/store/Observable":function(){define(["../_base/kernel","../_base/lang","../when","../_base/array"],function(f,l,t,p){f=function(e){function c(c,m){var d=e[c];d&&(e[c]=function(b){var a;"put"===c&&(a=e.getIdentity(b));if(k)return d.apply(this,arguments);k=!0;try{var h=d.apply(this,arguments);
t(h,function(g){m("object"==typeof g&&g||b,a)});return h}finally{k=!1}})}var m=[],f=0;e=l.delegate(e);e.notify=function(e,c){f++;for(var d=m.slice(),b=0,a=d.length;b<a;b++)d[b](e,c)};var d=e.query;e.query=function(c,k){k=k||{};var r=d.apply(this,arguments);if(r&&r.forEach){var b=l.mixin({},k);delete b.start;delete b.count;var a=e.queryEngine&&e.queryEngine(c,b),h=f,g=[],n;r.observe=function(b,c){1==g.push(b)&&m.push(n=function(b,n){t(r,function(d){var m=d.length!=k.count,s,l;if(++h!=f)throw Error("Query is out of date, you must observe() the query prior to any data modifications");
var t,u=-1,r=-1;if(void 0!==n){var x=[].concat(d);a&&!b&&(x=a(d));s=0;for(l=d.length;s<l;s++){var w=d[s];if(e.getIdentity(w)==n&&!(0>x.indexOf(w))){t=w;u=s;(a||!b)&&d.splice(s,1);break}}}if(a){if(b&&(a.matches?a.matches(b):a([b]).length))s=-1<u?u:d.length,d.splice(s,0,b),r=p.indexOf(a(d),b),d.splice(s,1),k.start&&0==r||!m&&r==d.length?r=-1:d.splice(r,0,b)}else b&&(void 0!==n?r=u:k.start||(r=e.defaultIndex||0,d.splice(r,0,b)));if((-1<u||-1<r)&&(c||!a||u!=r)){m=g.slice();for(s=0;d=m[s];s++)d(b||t,u,
r)}})});var d={};d.remove=d.cancel=function(){var a=p.indexOf(g,b);-1<a&&(g.splice(a,1),g.length||m.splice(p.indexOf(m,n),1))};return d}}return r};var k;c("put",function(d,c){e.notify(d,c)});c("add",function(d){e.notify(d)});c("remove",function(d){e.notify(void 0,d)});return e};l.setObject("dojo.store.Observable",f);return f})},"dojo/store/Cache":function(){define(["../_base/lang","../when"],function(f,l){var t=function(p,e,c){c=c||{};return f.delegate(p,{query:function(m,f){var d=p.query(m,f);d.forEach(function(d){(!c.isLoaded||
c.isLoaded(d))&&e.put(d)});return d},queryEngine:p.queryEngine||e.queryEngine,get:function(c,f){return l(e.get(c),function(d){return d||l(p.get(c,f),function(d){d&&e.put(d,{id:c});return d})})},add:function(c,f){return l(p.add(c,f),function(d){e.add(d&&"object"==typeof d?d:c,f);return d})},put:function(c,f){e.remove(f&&f.id||this.getIdentity(c));return l(p.put(c,f),function(d){e.put(d&&"object"==typeof d?d:c,f);return d})},remove:function(c,f){return l(p.remove(c,f),function(d){return e.remove(c,
f)})},evict:function(c){return e.remove(c)}})};f.setObject("dojo.store.Cache",t);return t})},"widgets/AttributeTable/table/FeatureLayerQueryStore":function(){define("dojo/_base/declare dojo/_base/lang dojo/_base/array esri/tasks/query esri/tasks/QueryTask ./FeatureLayerQueryResult".split(" "),function(f,l,t,p,e,c){return f(null,{queryUrl:"",idProperty:"id",data:null,_entityData:null,constructor:function(c){f.safeMixin(this,c);this.data=[];this._entityData=[];this.layer=c.layer;this.objectIds=c.objectIds;
this.where=c.where;this.orderByFields=c.orderByFields;this.totalCount=c.totalCount;this.batchCount=c.batchCount||25;this.idProperty=this.layer.objectIdField;this.spatialFilter=c.spatialFilter;this.layer&&this.layer.url&&(this.queryTask=new e(this.layer.url))},get:function(c){return this.data[c]},getIdentity:function(c){return c[this.idProperty]},query:function(e,f){var d=new p,k=f&&f.start||0,u=this.batchCount,q=null;"function"===typeof e?q=e(this._entityData):"[object Array]"===Object.prototype.toString.call(e)&&
(q=e);if(this.objectIds)q=q?q:this.objectIds,d.objectIds=q.length>=k+this.batchCount?q.slice(k,k+u):q.slice(k);else if(q&&0<q.length?d.objectIds=q.length>=k+this.batchCount?q.slice(k,k+u):q.slice(k):(d.start=k,d.num=u,d.where=this.where,d.geometry=this.spatialFilter,d.spatialRelationship=p.SPATIAL_REL_INTERSECTS),(k=f.sort)&&0<k.length)k=t.map(k,function(b){return b.attribute+" "+(b.descending?"DESC":"ASC")}),d.orderByFields=k;d.returnGeometry="esriGeometryPoint"===this.layer.geometryType;d.outFields=
["*"];var r=this.totalCount,k=null,k=!d.where;if(!(d.objectIds&&0<d.objectIds.length)&&k)return new c([]);k=this.queryTask?this.queryTask.execute(d):this.layer.queryFeatures(d);k.total=k.then(l.hitch(this,function(b){var a=0,h=this.layer.objectIdField;if(this.objectIds){if(!h)for(a=0;a<b.fields.length;a++)if("esriFieldTypeOID"===b.fields[a].type){h=b.fields[a].name;break}for(var g={},a=0;a<b.features.length;a++)g[b.features[a].attributes[h]]=b.features[a];b.features=t.map(d.objectIds,function(a){return g[a]})}for(a=
0;a<b.features.length;a++)if(b.features[a]){var c=b.features[a];b.features[a]=l.mixin(l.clone(c.attributes),{geometry:c.geometry});this.data[b.features[a][h]]=b.features[a];this._entityData.push(b.features[a])}b=b.features;return r}),function(){console.log("FeatureLayerQueryStore queryFeatures failed.");return 0});return new c(k)}})})},"widgets/AttributeTable/table/FeatureLayerQueryResult":function(){define("esri/main dojo/_base/lang dojo/_base/kernel dojo/_base/Deferred dojo/DeferredList dojo/_base/array".split(" "),
function(f,l,t,p){var e=function(c){function m(f){c[f]||(c[f]=function(){var d=arguments;return p.when(c,function(c){Array.prototype.unshift.call(d,c.features||c);return e(t[f].apply(t,d))})})}if(!c)return c;c.then&&(c=l.delegate(c));c.total||(c.total=p.when(c,function(c){return f._isDefined(c.total)?c.total:c.length||0}));m("forEach");m("filter");m("map");m("some");m("every");return c};return e})},"widgets/AttributeTable/setting/_build-generate_module":function(){define(["dojo/text!./Setting.html",
"dojo/text!./css/style.css","dojo/i18n!./nls/strings"],function(){})},"url:widgets/AttributeTable/setting/Setting.html":'\x3cdiv style\x3d"width:100%;"\x3e\r\n  \x3cdiv class\x3d"instruction"\x3e\r\n    \x3cp\x3e${nls.instruction}\x3c/p\x3e\r\n  \x3c/div\x3e\r\n  \x3cdiv data-dojo-attach-point\x3d"tableLayerInfos" class\x3d"table-layer-infos"\x3e\x3c/div\x3e\r\n  \x3cdiv class\x3d"table-options jimu-ellipsis"\x3e\r\n    \x3cul\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"exportcsv" checked\r\n        data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.exportCSV}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"expand" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.expand}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n      \x3cli\x3e\r\n        \x3cdiv data-dojo-attach-point\x3d"filterByMapExtent" data-dojo-type\x3d"jimu/dijit/CheckBox" label\x3d"${nls.filterByExtent}"\x3e\x3c/div\x3e\r\n      \x3c/li\x3e\r\n    \x3c/ul\x3e\r\n  \x3c/div\x3e\r\n\x3c/div\x3e\r\n',
"url:widgets/AttributeTable/setting/css/style.css":".jimu-widget-attributetable-setting{margin:0; padding:0; font-size:14px; width: 100%; height: 100%; position: relative; color: #596679;}.jimu-widget-attributetable-setting .instruction{font-size: 12px; margin-bottom: 10px;}.jimu-widget-attributetable-setting .show{width: 120px;}.jimu-widget-attributetable-setting .symbol{width: 200px;}.jimu-widget-attributetable-setting .table-layer-infos{width: 100%; height: 396px;}.jimu-widget-attributetable-setting .table-options ul{list-style-type: none; padding: 0;}.jimu-widget-attributetable-setting .jimu-checkbox{margin-right: 20px;}.jimu-widget-attributetable-setting .disable-checkbox{color: #e5e5e5;}",
"*now":function(f){f(['dojo/i18n!*preload*widgets/AttributeTable/setting/nls/Setting*["ar","cs","da","de","en","el","es","et","fi","fr","he","hr","it","ja","ko","lt","lv","nb","nl","pl","pt-br","pt-pt","ro","ru","sr","sv","th","tr","zh-cn","vi","zh-hk","zh-tw","ROOT"]'])}}});
define("dojo/_base/declare dijit/_WidgetsInTemplateMixin jimu/BaseWidgetSetting jimu/dijit/SimpleTable dojo/_base/lang dojo/_base/html dojo/_base/array dojo/on dojo/Deferred dojo/query jimu/dijit/Popup jimu/dijit/Message jimu/dijit/LoadingShelter ../utils".split(" "),function(f,l,t,p,e,c,m,v,d,k,u,q,r,b){return f([t,l],{baseClass:"jimu-widget-attributetable-setting",currentFieldTable:null,_allLayerFields:null,_layerInfos:null,_tableInfos:null,_delayedLayerInfos:null,_delayedLayerInfosAfterInit:null,
_unSpportQueryCampsite:null,startup:function(){this.inherited(arguments);this.config.layerInfos||(this.config.layerInfos=[]);this._allLayerFields=[];this._layerInfos=[];this._tableInfos=[];this._delayedLayerInfos=[];this._delayedLayerInfosAfterInit=[];this._unSpportQueryCampsite={};this.displayFieldsTable=new p({fields:[{name:"show",title:this.nls.show,width:"auto",type:"checkbox","class":"show"},{name:"label",title:this.nls.label,width:"60%",type:"text"},{name:"url",title:"url",type:"text",hidden:!0},
{name:"index",title:"index",type:"text",hidden:!0},{name:"actions",title:this.nls.actions,type:"actions",width:"20%",actions:["edit"],"class":"symbol"}],selectable:!0,autoHeight:!1});this.displayFieldsTable.placeAt(this.tableLayerInfos);c.setStyle(this.displayFieldsTable.domNode,{height:"100%"});this.shelter=new r({hidden:!0});this.shelter.placeAt(this.domNode.parentNode.parentNode||this.domNode);this.shelter.startup();this.shelter.show();b.readLayerInfosObj(this.map).then(e.hitch(this,function(a){this.own(a.on("layerInfosChanged",
e.hitch(this,this.onLayerInfosChanged)));this.own(v(this.displayFieldsTable,"actions-edit",e.hitch(this,this.editFieldsClick)));this.own(v(this.displayFieldsTable,"row-click",e.hitch(this,this._verifiedOnShowClick)));this.setConfig(this.config)}))},editFieldsClick:function(a){var b=k(".action-item-parent",a);if(b&&b.length)if(b=this.displayFieldsTable.getRowData(a),b.show){var g=parseInt(b.index,10);this.shelter.show();this._getLayerFields(g).then(e.hitch(this,function(b){this.openFieldsDialog(a,
b,g)}),e.hitch(this,function(a){console.error(a)})).always(e.hitch(this,function(){this.shelter.hide()}))}else var c=new q({message:this.nls.warning,buttons:[{label:this.nls.ok,onClick:e.hitch(this,function(){c.close()})}]})},_verifiedOnShowClick:function(a){var b=this.displayFieldsTable.getRowData(a),g=parseInt(b.index,10),c=null,c=this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?this.config.layerInfos[g]:this._layerInfos[g],g=-1<this._unSpportQueryCampsite.layerNames.indexOf(c.name||
c.title);b.show&&g&&(new q({message:this.nls.unsupportQueryWarning}),b.show=!1,this.displayFieldsTable.editRow(a,b))},_getLayerFields:function(a){return this._layerInfos[a].getLayerObject().then(e.hitch(this,function(c){var g=this._allLayerFields[a];c=m.map(c.fields,function(a){return{name:a.name,alias:a.alias,show:!0}});b.merge(c,g,"name",function(a,b){e.mixin(a,b)});return c=b.syncOrderWith(c,g,"name")}))},openFieldsDialog:function(a,b,c){var d=this._createFieldsTable(b,c);this.currentFieldTable=
d;var f=new u({titleLabel:this.nls.configureLayerFields,width:640,maxHeight:600,autoHeight:!0,content:d,buttons:[{label:this.nls.ok,onClick:e.hitch(this,function(){this._allLayerFields[c]=d.getData();f.close();f=null})},{label:this.nls.cancel,classNames:["jimu-btn-vacation"],onClick:e.hitch(this,function(){f.close();f=null})}],onClose:function(){f=null}});d.startup()},_createFieldsTable:function(a){for(var b=null,c={fields:[{name:"show",title:this.nls.fieldVisibility,type:"checkbox","class":"show",
onChange:e.hitch(this,function(a){var c=b.getData();if(!m.some(c,e.hitch(this,function(a){return a.show}))&&(new q({message:this.nls.fieldCheckWarning}),c=b.getRowData(a)))c.show=!0,b.editRow(a,c)})},{name:"name",title:this.nls.fieldName,type:"text"},{name:"alias",title:this.nls.fieldAlias,editable:!0,type:"text"},{name:"actions",title:this.nls.fieldActions,type:"actions",actions:["up","down"],"class":"symbol"}],selectable:!0,autoHeight:!1,style:{height:"300px",maxHeight:"300px"}},b=new p(c),c=0;c<
a.length;c++)a[c].show=void 0===a[c].show?!0:!!a[c].show,b.addRow(a[c]);return b},setConfig:function(a){this.config=a;this.displayFieldsTable.clear();this._allLayerFields=[];this._processTableData().then(e.hitch(this,function(a){this._init(a);this.shelter.hide()}),e.hitch(this,function(a){new q({message:a.message||a})}))},onLayerInfosChanged:function(a,b,c){"added"!==b||(!c||!a)||c.getSupportTableInfo().then(e.hitch(this,function(a){a.isSupportedLayer&&(this._layerInfos&&0===this._layerInfos.length?
this._delayedLayerInfos.push(c):this._layerInfos&&(0<this._layerInfos.length&&!this._getLayerInfoById(c.id))&&(this._delayedLayerInfosAfterInit.push(c),this._processDelayedLayerInfosAfterInit(this._delayedLayerInfosAfterInit)))}))},_processDelayedLayerInfosAfterInit:function(a){for(var c=this._layerInfos.length,g=0;g<a.length;g++){var d=b.getConfigInfoFromLayerInfo(a[g]);this.displayFieldsTable.addRow({label:d.name||d.title,url:d.layer.url,index:""+(c+g),show:d.show});this._allLayerFields.push(d.layer.fields);
this._layerInfos.push(a[g])}},_processDelayedLayerInfos:function(){0<this._delayedLayerInfos.length&&(m.forEach(this._delayedLayerInfos,e.hitch(this,function(a){this._getLayerInfoById(a.id)||this._layerInfos.push(a)})),this._delayedLayerInfos=[])},_processTableData:function(){var a=new d;b.readConfigLayerInfosFromMap(this.map,!0,!0).then(e.hitch(this,function(c){this._layerInfos=c;this._processDelayedLayerInfos();b.readSupportTableInfoFromLayerInfos(this._layerInfos).then(e.hitch(this,function(g){this._tableInfos=
g;this.config&&this.config.layerInfos&&0<this.config.layerInfos.length?(g=b.getConfigInfosFromLayerInfos(this._layerInfos),b.merge(g,this.config.layerInfos,"id",e.hitch(this,function(a,c){a.show=c.show;a.layer.url=c.layer.url;e.getObject("layer.fields.length",!1,a)&&e.getObject("layer.fields.length",!1,c)?(b.merge(a.layer.fields,c.layer.fields,"name",function(a,b){e.mixin(a,b)}),a.layer.fields=b.syncOrderWith(a.layer.fields,c.layer.fields,"name")):a.layer.fields=c.layer.fields})),this.config.layerInfos=
g,this._unSpportQueryCampsite.fromConfig=!0,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this.config.layerInfos),a.resolve(g)):(this._unSpportQueryCampsite.fromConfig=!1,this._unSpportQueryCampsite.layerNames=this._getUnsupportQueryLayerNames(this._layerInfos),a.resolve(b.getConfigInfosFromLayerInfos(c)))}),function(b){console.error(b);a.reject(b)})}),e.hitch(this,function(b){console.error(b);a.reject(b)}));return a},_getUnsupportQueryLayerNames:function(a){var b=[];m.forEach(a,
e.hitch(this,function(a){var c=this._getSupportTableInfoById(a.id);c&&!c.isSupportQuery&&b.push(a.name||a.title)}));return b},_init:function(a){for(var b=[],d=0;d<a.length;d++){var e=a[d].show&&this._getSupportTableInfoById(a[d].id).isSupportQuery;this.displayFieldsTable.addRow({label:a[d].name||a[d].title,url:a[d].layer.url,index:""+d,show:e});this._allLayerFields.push(a[d].layer.fields);this._unSpportQueryCampsite.fromConfig&&(e=(e=this._unSpportQueryCampsite.layerNames)&&-1<e.indexOf(a[d].name||
a[d].title),a[d].show&&e&&b.push(a[d].name||a[d].title))}this._unSpportQueryCampsite.fromConfig&&0<b.length&&new q({message:this.nls.unsupportQueryLayers+"\x3cbr\x3e\x3cbr\x3e"+b.toString()});this.config.hideExportButton?this.exportcsv.uncheck():this.exportcsv.check();this.config.initiallyExpand?this.expand.check():this.expand.uncheck();this._canUseOpenAtStart()&&(this.openAtStart?this.expand.check():this.expand.uncheck(),this.expand.status=!1,c.addClass(this.expand.domNode,"disable-checkbox"));this.config.filterByMapExtent?
this.filterByMapExtent.check():this.filterByMapExtent.uncheck()},_canUseOpenAtStart:function(){return this.closeable||!this.isOnScreen},_getLayerInfoById:function(a){for(var b=0,c=this._layerInfos.length;b<c;b++)if(this._layerInfos[b].id===a)return this._layerInfos[b]},_getSupportTableInfoById:function(a){for(var b=0,c=this._tableInfos.length;b<c;b++)if(this._tableInfos[b].id===a)return this._tableInfos[b]},getConfig:function(){var a=this.displayFieldsTable.getData(),b=[],c=a.length;if(this.config&&
this.config.layerInfos&&0<this.config.layerInfos.length)m.forEach(a,e.hitch(this,function(c,d){var e=this.config.layerInfos[d],f={};f.name=e.name||e.title;f.id=e.id;f.layer={};f.layer.url=a[d].url;f.layer.fields=this._allLayerFields[d];f.show=a[d].show;b.push(f)}));else for(var d=0;d<c;d++){var f={};f.name=this._layerInfos[d].name||this._layerInfos[d].title;f.id=this._layerInfos[d].id;f.layer={};f.layer.url=a[d].url;f.layer.fields=this._allLayerFields[d];f.show=a[d].show;b.push(f)}this.config.layerInfos=
b;this.config.hideExportButton=!this.exportcsv.getValue();this.config.filterByMapExtent=this.filterByMapExtent.getValue();this._canUseOpenAtStart()||(this.config.initiallyExpand=this.expand.getValue());return this.config}})});